### ISSUE TITLE
Problem with % of members have stated their position

### ISSUE THREAD

**Issue by Frittmann** [loomio/loomio#1595]
We've come across a repeatable anomaly in the results pane of a proposal, specifically in the text that states "x% of members have stated their position". The value appears to be out by 1. See the [discussion here](https://www.loomio.org/d/j6xH91Ea/loomio-seems-to-have-problems-adding-up) for more details.

**Comment by denjello** [comment]
If this is still an issue, this really needs to be examined and fixed. A voting platform with incorrect counts of voters is bad press.

**Comment by robguthrie** [comment]
Closing. It's really old. This stuff has been rewritten since then.

**Comment by Frittmann** [comment]
Can you provide a link to where "this stuff has been rewritten since then", please?

**Comment by robguthrie** [comment]
uhmm.. nope. I think I've been a bit hasty here. Sorry @Frittmann.

I'm currently wondering if this is caused by a special extension put in just for the internet party. Specifically, the is_suspended boolean on memberships...

I would like to hear if any groups outside of internet party are currently able to reproduce this problem.

**Comment by robguthrie** [comment]
closing as we cannot reproduce
