### ISSUE TITLE
% who have stated their position should reflect only those who can vote

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#1638]
It's easiest to explain this with an example. The Enspiral Foundation Board group has the three board members (who are group coordinators), and the company secretary and accountant in there as advisors (who don't vote). It's set up so members can't vote on proposals, only coordinators. So 5 total members, 3 voting members. But when you raise a proposal, it still counts participation out of 5, not 3. That % should be calculated based on people who are allowed to participate in voting, not total members, so when the 3 voting members have all stated positions it would say 100%.

**Comment by mc0e** [comment]
This also makes me wonder if it should be possible to set up users as having observer status for a group, without needing to use the group coordinator role to get this functionality.  It's not always going to be the case that everyone who can vote should be a coordinator.

**Comment by denjello** [comment]
I totally agree!
I would liken this problem to this issue: loomio/loomio/issues/1595
Is there a collection of issues dealing with voter counts? There should be.

**Comment by robguthrie** [comment]
Ohhhh.. this bug was introduced when we added the option only admins can vote (kinda yuck). 

We'll need a set of test cases for 
motion.did_not_vote
motion.did_not_voters
motion.members_not_voted
motion.percent_voted

in the context of a group where only admins can vote. 


It feels like we go this wrong somehow, (i agree with @denjello that observer status would be nice), but right now it's a bug that needs fixing.

**Comment by gdpelican** [comment]
I believe this has been taken care of in 1.0.
