### ISSUE TITLE
links in comments without ( http | https | www ) fail to link correctly

### ISSUE THREAD

**Issue by mixmix** [loomio/loomio#1704]
e.g. if I want to use the link trello.com/c/TycS5zmt 
- **In markdown** : it prepends the current page name to the link 
( https://www.loomio.org/d/ZdQzV1Cu/trello.com/c/TycS5zmt )

- **In-line** : it doesn't auto-link the link ... meaning users have to copy-paste

![image](https://cloud.githubusercontent.com/assets/2665886/4415703/bc093766-4530-11e4-9347-630ee09e0e73.png)

**Comment by denjello** [comment]
`trello.com/c/TycS5zmt` looks to people like am URL, but it is "tricky". 
`my.projects/app/assets/javascripts/discussions.js.coffee` doesn't look as much like an URL - but a lot of people out there might think so too. 

Expecting Markdown to regex a url without `http://` is kind of like trying expecting a letter to arrive without putting a postage stamp on the envelope. The fact that it is unable to craft a link from `<www.trello.com>` is however somewhat surprising.

http://www.loomio.org
www.loomio.org
loomio.org

I am really not sure that there is a reason to try and fix this, because the Markdown spec actually seems to require the use of a subdomain OR a protocol. If neither are provided it appends the link to the current folder. Maybe not the best solution out there - but it does mean that we need to inform people to use the whole link including protocol. That or an input field where they can paste a link and we try to parse it as an address...

**Comment by robguthrie** [comment]
@s01us what happens in the angular interface?

**Comment by gdpelican** [comment]
Closing due to ancientness. I believe 1.0 handles this alright.
