### ISSUE TITLE
delete comment not working

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1798]
can't delete any comments [in this thread](https://www.loomio.org/d/dvj8lWgX/keyboard-shortcut-to-post-comment-and-start-discussion), mine or others (I'm a coordinator)

![image](https://cloud.githubusercontent.com/assets/970124/5384684/80bf7d60-8120-11e4-86b3-fa732ddb930b.png)

**Comment by denjello** [comment]
Has this been fixed???

**Comment by robguthrie** [comment]
There is a bug with attachments... we're recording the attachment url in a complex way, and the ruby URL library can't handle some attachment urls because of it.... which is causing this bug.

The best fix would be to change the way we record attachments... the second best fix would be to find a way to parse the URL reliably.

**Comment by denjello** [comment]
Hmmm. Might this have something to do with unsafe filenames being used? We should definitely consider making the filename safe before uploading it. Unfortunately we can't really trust the browser to do this though. For example I just uploaded a file named `händ!#yés.png` which contains several characters that SHOULD NEVER be allowed in file names. Indeed, the preview failed and S3 threw an error on the requesting page. However, I could delete the comment... 

`https://loomio-attachments.s3.amazonaws.com/uploads/fd461aea39a8b9b95e94799675d43df6/h%C3%A4nd!#y%C3%A9s.png`
