### ISSUE TITLE
Pull out Loomio.org specific code into plugin

### ISSUE THREAD

**Issue by denjello** [loomio/loomio#1848]
in /config/routes.rb there are hard coded links to loomio.org:

```
  constraints(GroupSubdomainConstraint) do
    get '/about' => redirect('https://www.loomio.org/about')
    get '/privacy' => redirect('https://www.loomio.org/privacy')
    get '/purpose' => redirect('https://www.loomio.org/purpose')
    get '/services' => redirect('https://www.loomio.org/services')
    get '/terms_of_service' => redirect('https://www.loomio.org/terms_of_service')
    get '/third_parties' => redirect('https://www.loomio.org/third_parties')
    get '/try_it' => redirect('https://www.loomio.org/try_it')
    get '/wallets' => redirect('https://www.loomio.org/wallets')
  end

  get '/crowd'              => redirect('https://love.loomio.org/')

  get '/blog'       => redirect('http://blog.loomio.org')
  get '/press'      => redirect('http://blog.loomio.org/press-pack')
  get '/press-pack' => redirect('http://blog.loomio.org/press-pack')
  get '/roadmap'    => redirect('https://trello.com/b/tM6QGCLH/loomio-roadmap')
  get '/community'  => redirect('https://www.loomio.org/g/WmPCB3IR/loomio-community')
  get '/timeline'   => redirect('http://www.tiki-toki.com/timeline/entry/313361/Loomio')
```

I would think that this behaviour is something that should be turned on in `/config/environment/production.rb` or at least provided by a variable such as `config.action_controller.root_host`

**Comment by rdbartlett** [comment]
I agree this is not ideal, especially with common path names like /about and /blog. Rather than making any piecemeal changes though, I'd like to see a comprehensive solution, a thoroughly designed approach to solving the identity problem for each hosted instance. It's important that loomio.org has a strong identity, and it's important that people can easily host their own instance without confusing that identity. In my opinion, we haven't yet resolved that tension.

@robguthrie and I did a 'first pass' design for this last year, which would be good to review. Basically the plan we came up with was that the site logo and footer (which is where most of those links are) would be customisable for each instance. 

Additionally, any reference to "Loomio" throughout the app (and the emails in particular) should be replaced by the hostname, e.g., rather than "view this discussion on Loomio", it would read, "view this discussion on loomio.example.com"

I wonder if you've had any thoughts about this @denjello?

**Comment by denjello** [comment]
After just a day or so wrapping my head around the amazing structure of loomio, I have begun to notice that there are quite a few places like in the locale yamls, the views and even in the models that include things like links and email addresses that really should be centralised.

Here are a few examples:
```
/config/locales/frontpage.de.yml
desc_html: "Loomio ist als freie Software <a href=\"https://github.com/loomio/loomio\">Open Source</a>, damit jeder überall an Entscheidungsprozessen teilnehmen kann."

/app/views/attachments/new.html.haml
= hidden_field_tag :redirect, 'http://loomio.dev/something'

/app/models/user.rb
where(email: ['contact@loomio.org', 'contact@loom.io'])
```
I have actually faced this exact problem in a different project, and the "easier" solution was to bite the bullet and abstract strings, hard links (& colors!!!) out of the code and into the config. As the code base continued to mature I was thankful that I had done this already because it made things easier to patch through to the front end from the database so that users could have GUI control over certain things...

I think that the fastest solution would be to instantiate a `/config/identity.rb` that includes all those things that would be useful for identifying & possibly styling the specific instance. Once the codebase has been purged of these strings the next iteration would be to possibly abstract "features" out of the config files and into the database...

**Comment by s01us** [comment]
That sounds like a nice approach.

**Comment by robguthrie** [comment]
My thinking about this has been that Loomio itself should be a rails engine, and there should be a surrounding application that brings in these kind of pages/functions..

**Comment by robguthrie** [comment]
This is still a big problem we should address

**Comment by gdpelican** [comment]
plugins. Plugins! PLUGINS!!!

Rebranding this as 'pull out loomio.org specific stuff into a plugin'

**Comment by gdpelican** [comment]
Let's have a chat about this today @HSalmon

**Comment by robguthrie** [comment]
oooohhh yea

**Comment by HSalmon** [comment]
Done!
