### ISSUE TITLE
Language switcher default from browser language?

### ISSUE THREAD

**Issue by peteruithoven** [loomio/loomio#1858]
Could it be that the language selector on the bottom of for example the sign up form always defaults to English? 
Could this use the language set in the browser settings?

**Comment by denjello** [comment]
Strangely the "best_cachable_locale" (which is also spelled incorrectly btw.) is to blame here I believe.

in `app/helpers/locales_helper.rb` it reads: 
```
  def best_locale
    if user_signed_in?
      best_available_locale
    else
      best_cachable_locale
    end
  end

  def best_available_locale
    selected_locale || detected_locale || default_locale
  end

  def best_cachable_locale
    selected_locale || default_locale
  end
```

This change worked for me as a quick fix:
```
  def best_cachable_locale
    selected_locale || detected_locale || default_locale
  end
```

I assume that this was done to improve anonymous-user  performance, but I find it to be a bit of an anti-pattern. Which is why I would recommend simplifying the first snippet into the following:

```
  def best_locale
    selected_locale || detected_locale || default_locale
  end
```

What do you think?

**Comment by denjello** [comment]
To make another comment about this language switcher, it is mysteriously missing from the landing page when not logged in.

**Comment by denjello** [comment]
@gdpelican -> close?
