### ISSUE TITLE
"Contact us" modal is broken

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1883]
On production, a click on the "Contact us" link in the app should be caught by the Intercom javascript, which opens a nice friendly modal. Recently this has stopped working. I talked to customer support at Intercom and they said it's most likely that some new javascript we've installed is interfering with it. Any ideas?

**Comment by gdpelican** [comment]
Appears to be a desktop-only bug, strangely. Don't think we've put any new javascript into beta a while, but could be wrong.

**Comment by gdpelican** [comment]
We have two contact us links on a given page, one for desktop and one for mobile. They both have the same id:

```
<a href="mailto:9075f281e2a66ab40cb5dc9a16aa61cd88cecd65@incoming.intercom.io" id="Intercom"><i class="fa fa-question-circle"></i>Contact us</a>
```

They both have id="Intercom", which means one of them is getting overridden (in this case, the desktop one)

Ideally they'd have a class we could apply to make the modal open, instead of an id, so that we can have multiple on the same page.

**Comment by rdbartlett** [comment]
Ok yep that will be the problem then, that explains why it works in mobile
and not in desktop. I don't understand why there are two? is that because
of the dumb way I made the navbar?

On 11 February 2015 at 14:16, James Kiesel <notifications@github.com> wrote:

> We have two contact us links on a given page, one for desktop and one for
> mobile. They both have the same id:
>
> <a href="mailto:9075f281e2a66ab40cb5dc9a16aa61cd88cecd65@incoming.intercom.io" id="Intercom"><i class="fa fa-question-circle"></i>Contact us</a>
>
> They both have id="Intercom", which means one of them is getting
> overridden (in this case, the desktop one)
>
> Ideally they'd have a class we could apply to make the modal open, instead
> of an id, so that we can have multiple on the same page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/1883#issuecomment-73818887>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>

**Comment by denjello** [comment]
I have no way of testing this, but it might work:

The html page has the following javascript injected into it:
`  window.intercomSettings = {... {"activator":"#Intercom"} ... };` 

The readme at https://github.com/intercom/intercom-rails shows this option.
```
<% if logged_in? %>
  <%= intercom_script_tag({
    :widget => {:activator => '#Intercom'}
  }) %>
<% end %>
```

Change :activator to a class like `.Intercom` instead of `#Intercom` in 
`app/views/application/_intercom_tracker.html.haml`

```
- if current_user_or_visitor.is_logged_in? && ENV['INTERCOM_APP_ID']
  = intercom_script_tag({:widget => {:activator => '.Intercom'}})
```

And your references to #Intercom to > .Intercom

**Comment by HSalmon** [comment]
Can do :)

**Comment by rdbartlett** [comment]
Thanks! :balloon:

On 20 February 2015 at 10:07, HSalmon <notifications@github.com> wrote:

> Can do :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loomio/loomio/issues/1883#issuecomment-75136051>.
>



-- 

Richard D. Bartlett
Loomio co-founder
rich@loomio.org

<http://loomio.org/>

**Comment by robguthrie** [comment]
fixed
