### ISSUE TITLE
Why is Google indexing pages with an explicit locale in the URL?

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1893]
See for instance:

![image](https://cloud.githubusercontent.com/assets/970124/6138518/a77a7210-b1e6-11e4-898b-0eaa6669053f.png)

**Comment by denjello** [comment]
I noticed this too: loomio/loomio/issues/1858 I believe it has to do with the way that the site is crawled by bots. (They start at https://loomio.org/ and the VERY first link that the bot will find is: 
```
<a href="?locale=de">Diese Seite auf Deutsch</a>
```
The bug is that the get request gets tacked on to all links UNTIL the user changes the language with a dropdown on a different page...

**Comment by rdbartlett** [comment]
So if we just put ```rel="nofollow"``` on that link it will likely fix it?

**Comment by denjello** [comment]
Yeah, that is a start, however if anyone anywhere publishes a link to `flying-animals?locale=sr` then it will be crawled. And once it has been crawled... Yeah. Maybe you could try logging into the google webmaster toolbox or whatever it is called and have a look at what has been indexed - maybe there is still an option to clean it up...

**Comment by robguthrie** [comment]
I wonder if this is something we can fix via robots.txt

I feel like we don't quite know what we're doing though. Would be great to
have an SEO expert explain some best practices.

**Comment by robguthrie** [comment]
I've just this morning commited a change which removes the "copy the locale parameter from the url to all links being generated" code from the system.

This means that pages loaded with locale=xx in them will no longer carry the locale through to other pages. This should be fine for most use cases, because we detect browser locale when rendering all pages anyway, and I think that the use case for inserting locale into the url is mostly for translators.

Anyway, I'm confident this will prevent a lot of the support issues we get, as well as these SEO problems... but we'll have to wait a little bit and see. Should I close the issue in the meantime @gdpelican ?

**Comment by gdpelican** [comment]
Yarp sounds good.

**Comment by denjello** [comment]
@robguthrie NICE!
