### ISSUE TITLE
Wrong timezone in "Yesterday on Loomio" email

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#1918]
The motion.closed_at time is being rendered in UTC, when it should be in my local timezone. E.g. This proposal closed at 9pm NZDT but in the email it says 8am

![image](https://cloud.githubusercontent.com/assets/970124/6235106/ccd6294c-b744-11e4-9dd9-ef1ff8330024.png)

**Comment by robguthrie** [comment]
Yikes, Thanks @rdbartlett

**Comment by robguthrie** [comment]
This might be fixed by adding .in_time_zone to app/views/thread_mailer/_motion.html.haml

```
%b= t(:closed) + " " + time_formatted_relative_to_age(motion.closing_at.in_time_zone)
```

But.. that does not seem right to me. Are times in any of our mailers localised? I wonder if they are not.

I think a better approach might be to do what we do when we set the locale... wrap the mailer in a timezone block:

```
Time.use_zone(current_user.time_zone, &block)
```

As we do in UserMailer and many many more places.. (copied from UserMailer):

```
      I18n.with_locale(locale) do
        mail to: user.email,
             subject: t("email.missed_yesterday.subject"),
             css: 'missed_yesterday'
      end
```

So I'm thinking that we make our own `mail` method, which looks something like this:

```
def localized_mail(locale, time_zone, options)
  I18n.with_locale(locale) do
    Time.use_zone(time_zone) do
      mail options
    end
  end
end
```

**Comment by s01us** [comment]
starting into this

**Comment by s01us** [comment]
it's gonna also use `in_time_zone`

```ruby
Time.use_zone( time_zone) {  time_from_database.in_time_zone }
```

**Comment by gdpelican** [comment]
Can anyone confirm if this is still a thing?

**Comment by gdpelican** [comment]
Closing as ancient. Happy to reopen if someone sees it again.
