### ISSUE TITLE
Inviting someone already in a group re-notifies them

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2094]
If you invite someone to a group who is already a member of that group, the app will notify the user that they have been added. Also the inviter sees a "member added" message. The system should know if that use is already a member of the group and not notify them (which could confuse the user who will think they weren't already in the group previously), and should display "member already in group" to the inviter. 

I think this is a relatively common situation actually... for example I want to invite a whole list of event attendees to a Loomio group and a subset of them are already members. Short of manually cleaning the email list, if I just invite them all the ones who are already in there will get a confusing notification.

A good example would be how Google Groups does this... if you invite a list of 10 people and 3 are already in the group, you will see a message that says "7 people added, 3 already in group", and only the new members will get notified.

**Comment by alannaloomio** [comment]
@HSalmon and I tested this by re-inviting me to the Loomio Community group and I did get a notification.

**Comment by robguthrie** [comment]
Great bug report. Thank you!

**Comment by zacharystenger** [comment]
I was looking into this issue and have an idea of how to fix it.  
In ``InvitationsController#create`` we want to check if any of the users (``@invite_people_form.members_to_add``) are already in the group before we call ``MembershipService#add_users_to_group`` and ``InvitationService#invite_to_group``.  To do this I was thinking of adding a new private method to the ``InvitiationsController`` that loops through the users checking if ``group.has_member?(user)`` which calls a new method in the ``InvitePeopleForm`` which would remove them from ``members_to_add`` and ``emails_to_invite`` (since these are used throughout ``InvitationsController``) and return all the users not re-invited (to be used to display a proper flash message).  
Feedback would be much appreciated before I starting writing tests & coding.  Thanks!
