### ISSUE TITLE
wysiwyg/preview of markdown?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#2742]
i remember reading somewhere you were planning to add some sort of wysiwyg/preview markdown editor on context and comments, but couldn't find anything... is there some progress on this?  i've done some research, [pen](https://sofish.github.io/pen/) seems to be more complete, but i'm unsure if it sends the server html or markdown :P 

[there're more resources here](https://github.com/rhythmus/markdown-resources/blob/master/markdown-tools.md)

**Comment by gdpelican** [comment]
My current thinking, which may or may not be the thinking of the team, is
that it while it would be super great to find a nice library that would
slide in and just work without fuss, finding something that will fit us
perfectly and expand in the ways we'll want it to expand,
functionality-wise, will be really tough and that a custom implementation
might need to happen.

Anyway it's pretty high up on the roadmap at the moment, so we'll get to it
soon.

**Comment by rdbartlett** [comment]
Awesome thanks for the research @fauno! I will throw some more things into the pot:

I want to get away from thinking about a "text editor" for a second, and think about a "messenger". 

It's becoming increasingly clear to me that the web is made much more inclusive and accessible and fun and engaging when you support messages of all kinds: images, audio, and video. 

I had a meeting with Deaf Aotearoa this week, where I learnt how asynchronous video message delivery services provide tremendous value to the Deaf community, who primarily communicate through sign language. The example they gave was an app called [Glide](http://www.glide.me/). Facebook was another example, where the support for video messages has provided breakthrough value for an otherwise disconnected community.

We've also been working with people who are blind, and considering the audio experience of Loomio. Telegram does a beautiful job of recording and sending audio messages. There is a microphone icon alongside the primary text input. Click and hold to record a message. Release to send. My 3 year old niece regularly sends me messages this way.

It's not just about people with disabilities though: everyone prefers to communicate in different ways. Right now we're having a big hefty discussion in one of my Loomio threads, and one of the most articulate, intelligent, literate people I know is saying, "arrrgh I can't write about this, I need to say it out loud!"

So supporting all kinds of expression is a lovely dream, and the job is to figure out the journey from here to there.

Here's a rough attempt at an ordered list of requirements I have for Loomio's messenger. 

1. It should be easy to format a big text post with links and lists and headings etc: I want to see exactly what the post looks like before I press Submit (i.e. either WSYWIG or Preview).
2. Good support for files: drag-and-drop to make attachments; 
3. Good support for images: preferably drag-and-drop to include images inline; even more preferably paste from clipboard to upload inline image.
4. Make it multimedia: audio and video messages are treated as first-class options.
5. Make it expressive: e.g. support for emojis in the body of the message, and as responses (a la Slack).

I'm hoping to do some research and design on this question next week. 

Very keen to hear from lots of people on this topic. [This article from Intercom](https://blog.intercom.io/why-we-built-our-message-editor-twice/) made me scared about building a custom text editor, so I want to make sure we understand the UX before we build anything big :)

**Comment by robguthrie** [comment]
Wonderful write up Rich. Thanks and I agree. Minor detail but along with
DnD for files.. clipboard support so I can just CMD+V images (and possibly
other media). Github and Trello support this.

**Comment by rdbartlett** [comment]
@robguthrie I think I said that: "paste from clipboard to upload inline image."

**Comment by gdpelican** [comment]
I've had a mild first pass at something like this; which will eventually go into our design pipeline and become an actual thing:

http://g.recordit.co/0suiclgWba.gif (ignore the bug at the end >.>)
https://github.com/gdpelican/loomio_comment_preview

**Comment by gdpelican** [comment]
This is now live as an experimental plugin in the Loomio community and Enspiral groups. Should be coming your way as a feature soon!
