### ISSUE TITLE
'Comment liked' notification doesn't take me to the comment if I'm already on that thread page

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2770]

**Comment by gdpelican** [comment]
Yeah, knew this would come up eventually. This is tricky because of the possibility that you're navigating to something way out of the existing event window.

Easiest thing might actually be to reload the page, while the more complicated thing would be to clear out the existing event window and re-request it with the given comment id. Thoughts @robguthrie?

**Comment by rdbartlett** [comment]
Let's fix this on #2946.

**Comment by robguthrie** [comment]
uhm... I would not support reloading the page, but I reckon there must be a
way for the ScrollService to register what's happened here and do it's
thing..  Happy to put it off for a while.. the router issue is such a pain,
but I think we're really close to getting a new angular router release
backported from 2.0
