### ISSUE TITLE
Drafts do not work on editing 

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2807]

**Comment by gdpelican** [comment]
Uh, on editing what? I'd really appreciate a little more detail in these 'bug reports' @rdbartlett

**Comment by rdbartlett** [comment]
Sorry for the brevity, was throwing notes down in a meeting. I saw this not
working on editing comments, but Rob believes it is the same for editing
anything.

**Comment by gdpelican** [comment]
This is actually intended behaviour at the moment... I found it really annoying to open up an edit modal, change a bunch of things, and then go back only to find them still there.... I kinda expected it to be a 'reset' to close the modal.

So I think this needs a little design, and a 'discard draft' button somewhere... it can't be as silent as the create draft stuff, because when you go to edit something, I think you expect it to start off the way it is.

**Comment by robguthrie** [comment]
Hrrmm.. I see your point. In that case I think we need to put the confirm
cancel back in there.

**Comment by gdpelican** [comment]
Yarr, totally agree.

**Comment by gdpelican** [comment]
Closing for now, I'll put a card on the roadmap for confirm cancel.
