### ISSUE TITLE
No link is available towards general information about Loomio, once connected

### ISSUE THREAD

**Issue by pgerland** [loomio/loomio#2849]
Once you are connected as a member, I couldn't find a way to get to loomio.org, but by disconnecting.

Even if you type www.loomio.org in the address box, you are redirected toware www.loomio.org/dashboard.
The url https://www.loomio.org/about is accessible manually when connected.

It would be great, especially for new members, to give acccess to the presentation of Loomio by clicking the Loomio logo in the upper ribbon.

Adding a link towards https://www.loomio.org/about (maybe with a _blank target)  should require no change in the site design.

Giving access to the main presentation (https://www.loomio.org) should probably require changes to the site design.

**Comment by gdpelican** [comment]
Hmm, I think I agree with this... there have been a few times where I've wanted to view the home page but couldn't because I was logged in.

That being said, most sites work this way; the marketing page is just that - for marketing. I'd be in favor of exposing /marketing to logged in users, so people can go there if they want to.

**Comment by rdbartlett** [comment]
Thanks for this feedback, we totally need to fix this. I'm going to suggest this will be fixed when we have the sidebar.
