### ISSUE TITLE
Images rendering way larger than width of discussion

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#2871]
If you upload a large image, it displays at full size, breaking the layout of a thread. Seems like it should display at the same width as the discussion, with an option to click for full size.

Example:

![screen shot 2016-01-13 at 4 45 30 pm](https://cloud.githubusercontent.com/assets/5498878/12284550/4598b0ce-ba15-11e5-84ed-c3db331db344.png)

**Comment by gdpelican** [comment]
Hrrrm.... that is odd. That thread looks like this for me:
![screen shot 2016-01-13 at 8 02 31 pm](https://cloud.githubusercontent.com/assets/750477/12287333/ac9bbb52-ba30-11e5-9fdb-06a66cac7cb5.png)

@robguthrie @HSalmon are you able to repro this? I wonder if Alanna's hanging on to an old asset somehow.

**Comment by robguthrie** [comment]
Yep I see the bug on Firefox latest.

@gdpelican it looks like there are 2 problems here. I expected that we'd resize/cut a new image for inline display.. say 640px or so wide.. And the second problem is the style for that attachment preview is not being recognised by FF.  ... we're using maxwidth:100% .. changing this to width: 100% fixes it.

**Comment by gdpelican** [comment]
Width 100% is no good, because it means that images get stretched to the
width of the thread port, which we don't want for portrait-shaped images.

Looks like FF doesn't support inline element max-width, so the fix is to
make the attachments not inline block when they're in the thread, but keep
them inline when they're previews (before the comment has been posted)

It should be serving a resized image, so that's a bug too.

Wee!

**Comment by gdpelican** [comment]
Upon further inspection, this particular image was uploaded by a non-angular user, so all the images are full-sized because beta doesn't do that. All the more reason to shut beta down in the near future. :8ball:
