### ISSUE TITLE
Subgroup setting descriptions inaccurate for secret groups

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#2899]
"anyone can find this subgroup, see who's in it, and ask to join." — should read something like "Members of Test on trial can find this subgroup, see who's in it, and ask to join."

![image](https://cloud.githubusercontent.com/assets/1380991/12660577/52a90abe-c679-11e5-9506-c7e10b9545b9.png)

To my mind, using the language 'public' is also not quite right in this context, as the public will never be able to see anything in or about a subgroup of a secret group.

**Comment by rdbartlett** [comment]
This should be fixed by putting `is_subgroup` of hidden parent into client logic.

* remove the option to create Open subgroup of Secret parent
* remove "allow public threads" from any subgroup of a secret parent
* "Anyone" should be "Members of Test"

**Comment by toupeira** [comment]
@rdbartlett actually I think "Open" (or at least the "How do people join?" sub-form) does make sense for a sub-group of a closed/secret parent, if I want parent members to be able to join without confirmation.

Note that I just suggested the opposite in https://github.com/loomio/loomio/issues/2938#issuecomment-183511587, but I forgot about the confirmation part :)

**Comment by robguthrie** [comment]
Just chirping in here to say that I'm adding a bunch of tests for the group form today. I've found a few bugs already. I'll report back here with what I found, tomorrow.

**Comment by rdbartlett** [comment]
Thanks for the thought @toupeira 

I did a major design project on this last year. You can [read my reasoning here](https://docs.google.com/document/d/1ptGmf6HYH8g_dQM_-xuB6SrEE0IWpY9Mik6z4v7yLOY/edit?usp=sharing) to get full context. Basically, I think **Secret** should always mean the group is only known to people I tell about it, and **Open** should always mean all the content is public on the web. 

I agree with your suggestion that it would make sense to have a subgroup of a Secret parent where any member can join without confirmation, but if we can, I'm keen to not pollute the meaning of the words **Secret** and **Open**.

**Comment by toupeira** [comment]
@robguthrie good to hear :+1: 

@rdbartlett thanks for linking that document which clears things up nicely, I agree that the definitions shouldn't be polluted further and was reluctant to suggest it at first. So if I understand correctly this is what I want (in italics):

> **Closed subgroup of secret parent**
> Group visibility: hidden from the public AND *visible to parents*;
> Thread privacy: private threads OR *visible to parents*; 
> Joining: parent members can *join by request* OR by approval OR anyone can join by invitation.

And all that's missing is the ability to "join by request".

I think the "needs approval" permission should be a checkbox on all levels, instead of only the radio buttons on "Open".

**Comment by mhjb** [comment]
+1 to that @toupeira

**Comment by rdbartlett** [comment]
Yeah I think I'm +1 to that too :)

**Comment by robguthrie** [comment]
@toupeira the group form fixes are live now. I hope that clears up most of the confusion.

I'm just now catching up on what you're requesting. I see you want a group that is Open to members of the parent group (I think of this as the Organisation), but otherwise secret, and you want to be able to select per thread if the members of the parent can see the thread or not?

**Comment by toupeira** [comment]
@robguthrie yep pretty much, also see my [Loomio discussion here](https://www.loomio.org/d/Rg4rW70Y/permission-model-for-use-in-a-company). Thanks a lot for the fixes, will try them out soon!

**Comment by rdbartlett** [comment]
Woohoo thanks Rob!
