### ISSUE TITLE
Slack notification has proposal title where thread title should be

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#2909]
![image](https://cloud.githubusercontent.com/assets/970124/12768970/b89135d8-ca78-11e5-9c33-e445f8e9cdf3.png)

See the proposal title is included twice in this notification. The first string should be the thread title.

**Comment by yhordi** [comment]
I was hoping to take this as my first contribution, though I am having a difficult time finding out where in the codebase the pieces that fit together with slack are, or how to test their output. Would you be able to give me some direction as to where I might look?

**Comment by gdpelican** [comment]
Hey @yhordi 

Take a look at this for how to set up a slack integration on your instance:
https://loomio.gitbooks.io/tech-manual/content/setup_slack.html

The offending code is likely in the `app/models/slack/` folder; those files are building a JSON payload and shooting it off to an endpoint you provide on your Webhook model.

Also, we're pretty imminently moving this functionality to a plugin, so if you do find a fix it might be nice to PR it on the [plugin repository](www.github.com/loomio/loomio_webhooks) as well.

Thanks for your help!

**Comment by yhordi** [comment]
Awesome! I'll take a look. 
Thanks for all the helpful info.

**Comment by gdpelican** [comment]
I just had a wander through this, and went 'oh geez, code I wrote a year ago, gross!'

Anyway, I think what we want here is to override `slack/motion_closing_soon.rb#text` the same way we do in `slack/new_discussion.rb#text`, to show the discussion title in that field rather than the proposal title, which is maybe-less-than-sensible default defined in `slack/base.rb`.
