### ISSUE TITLE
Allow slack integrations to be set up by coordinators

### ISSUE THREAD

**Issue by Connoropolous** [loomio/loomio#2921]
I'm just going through this process with Hylo, and I know Loomio has the slack integration as well, check out this open pull request to see the flow I mean: https://github.com/Hylozoic/hylo-node/pull/81

:tada:

**Comment by Connoropolous** [comment]
As far as I can remember, currently only sysadmins can add slack integrations? Like in Hylo, with the increased simplification of the process, this should more easily allow the addition of this feature for community moderators within loomio to be able to manage their integration themselves, without having to go through the rather complex process previously involved  of manually setting up an incoming webhook

**Comment by gdpelican** [comment]
That sounds great. All of our current slack integration stuff is in the process of being pulled out into a plugin, which lives here: http://github.com/loomio/loomio_webhooks. Probably a good call to read up on our new plugin architecture here: https://github.com/loomio/loomio/blob/plugins-effyeah/plugins/README.md

However you'd be interested in implementing this, I'd say we probably want to tack it on to that plugin (or make a new plugin which extends it), and that we want to keep it slack agnostic as much as possible (since it's not really a slack integration so much as webhook functionality with some slack-specific json payloads)

**Comment by gdpelican** [comment]
Also keep in mind that since Loomio.org is monolithic and will likely stay that way for a while, I'm not sure storing slack credentials in ENV will work, since many different slack apps will want to communicate with a single instance.

Honestly I think the next step for usability in this direction would be to have a form in the angular interface which allowed coordinators to put in a webhook URI, specify that it's a slack webhook, and which events they'd like to receive. We already have an admin panel for this, but since it's a kinda-sorta 'premium feature', we haven't pulled that out to the angular interface just yet.

**Comment by Connoropolous** [comment]
@gdpelican yes, the slack credentials wouldn't accumulate, there is just one for the "Loomio" app. 

My thoughts are that both could be implemented alongside one another. The more deeply customizable thing that is simply the storage of a webhook, platform agnostic, and the really cut and dry, anybody can do it, automated user flow for adding slack :)

I'll definitely have to read up on the plugin architecture to understand how that would be able to happen

**Comment by Connoropolous** [comment]
I've got it working with the webhooks plugin now, and read the plugin docs. 

Yeah, I'd be interested to try and add the functionality I was outlining to the plugin. 

The benefit to users is that they don't ever have to look at the 'custom integrations' panel of their slack team. They just look in 'apps' , they see Loomio, and they add it or remove it. Internally, the Loomio slack app is configured to request 'incoming webhook' access. 

You can still keep all the fundamental code slack agnostic, while highlighting it as a first, and most common usage. On that note, I was noticing that the WebhookSerializer class is still in the main repo, and also that it is tailored specifically to what slack webhooks should look like. It made me think that the default for them could just be to send the details of the event that occurred. Does that make sense?

(And even crazier, down the road, we could build a slack bot (or an open source equiv) that starts to make loomio conversational)

**Comment by gdpelican** [comment]
Anyone tracking this still might be interested in visiting loomio.org/slack/install (which is as yet a beta feature, but does allow coordinators to sync slack with their groups)
