### ISSUE TITLE
Join subgroups of secret parents without approval

### ISSUE THREAD

**Issue by toupeira** [loomio/loomio#2951]
Follow-up issue to https://github.com/loomio/loomio/issues/2899#issuecomment-183980261

See [design doc](https://docs.google.com/document/d/1ptGmf6HYH8g_dQM_-xuB6SrEE0IWpY9Mik6z4v7yLOY/edit?usp=sharing) and [mockup](https://projects.invisionapp.com/share/MW4OZVNCT#/screens):

![selection_001](https://cloud.githubusercontent.com/assets/6501/13060566/db9bc9ee-d432-11e5-88bc-d669b750bfb9.png)

Currently the "How do people join?" section isn't available and would be very useful to have.

**Comment by toupeira** [comment]
It would be also nice to have a *"Members of {{Parent Group}} can participate in threads in this subgroup"* permission on subgroups, so users don't have to explicitly join when they want to chip in on a random discussion, and can thus avoid confusion/email overload/having to change notification settings.

Looking at [`Ability#user_is_member_of?`](https://github.com/loomio/loomio/blob/dcb105b3eec993ab9b5d3a57185accc8d816f517/app/models/ability.rb#L4) I wonder if this could be implemented with a bit of SQL, to check for membership on the parent instead of the subgroup when this permission is active.

Two questions come to mind:
- Are comments / votes / events somehow tied to the group membership?
- If yes, would it be feasible to reuse the parent membership in those cases?

**Comment by gdpelican** [comment]
Hm, I keep breezing by this, and haven't quite gotten together enough thoughts for a response.

Some thought fragments:
- Our group privacy settings have just moved from being overly complicated to pretty simple. I'd really love to get to a place where the privacy settings are super-dead simple, and then complicate from there if need be (and probably through plugins rather than complicating core)
- Comments, votes, and events aren't tied to a membership, but we do check that the 'actor' has permission to perform the action in the services level (ie `discussion_service.rb`). A SQL query could work, but again I worry about that added complexity
- This feels like it's calling out to the desire for 'Decision first Loomio', or 'one off decisions', which is a doodle-like reimagining of the discussion/proposal we've been kicking around a bit this year.

Mockups here: https://projects.invisionapp.com/share/U24ZUNDWG#/screens/116645403

In my head, this allows for the 'one-off' / 'fuzzy membership' decision which I think you're describing, without having to complicate something that's really burned us by being really complicated in the past.

**Comment by toupeira** [comment]
@gdpelican no hurries, thanks for your thoughts! Let me try and chip away at your doubts a bit :)

> Our group privacy settings have just moved from being overly complicated to pretty simple. I'd really love to get to a place where the privacy settings are super-dead simple, and then complicate from there if need be (and probably through plugins rather than complicating core)

I just don't see the rationale behind having the "How do people join" setting only available on "Open" groups, it makes sense to not have it on "Secret" (because you obviously can't join a group you can't see) but I would argue that having it on "Closed" as well would actually *reduce* complexity.

> Comments, votes, and events aren't tied to a membership, but we do check that the 'actor' has permission to perform the action in the services level (ie discussion_service.rb). A SQL query could work, but again I worry about that added complexity

Ok scratch that idea then :) A different approach to avoid this issue would be having "shadow" memberships, i.e. when a user is added to a parent group they're also added implicitly to child groups, but won't be visible as members and won't get the default group notifications. I might try this in a plugin.

> This feels like it's calling out to the desire for 'Decision first Loomio', or 'one off decisions', which is a doodle-like reimagining of the discussion/proposal we've been kicking around a bit this year.

Not quite, it goes back to [my Loomio discussion](https://www.loomio.org/d/Rg4rW70Y/permission-model-for-use-in-a-company), my main concern is that people have to join the whole group to participate in a single discussion, which brings with it some things like the group notifications. But that's just a minor annoyance that can be circumvented with the available options, unlike the requirement for having to approve the membership first.

**Comment by toupeira** [comment]
I just realized I can't even add members directly as group coordinator or through the administration, it seems I can only trigger invitations which the users have to accept first :cry:

I have a feeling you're not dog-fooding the secret groups enough, I think you'd see my pain points pretty quickly if you did ;-)

**Comment by gdpelican** [comment]
Er, you can add members of the parent group directly to a subgroup if you're a coordinator:
http://g.recordit.co/jHR73KU74c.gif

We've used secret groups pretty extensively internally, and they've met our needs (and the needs of our customers) pretty well thus far. We welcome the feedback, but I'd suggest that if this is something you feel strongly about, you have the agency to be the change you want to see. :)

I for one would super-welcome [a plugin](https://github.com/loomio/loomio/tree/master/plugins) for some more advanced privacy settings.

**Comment by toupeira** [comment]
@gdpelican yes sorry I was talking about the (also secret) parent group, I don't have the option there of adding members directly like on subgroups, which again seems like a needless distinction to me and an opportunity to reduce complexity ;-)

I would be totally willing to implement these changes in core, if you're saying you'll accept them:

- Add the "How do people join" setting on closed parent/sub-groups
- Allow adding members directly on all parent/sub-group levels

I'd rather not do this as a plugin because it's a sensitive area and not something I want to have broken by a Loomio update. And it also seems a lot more straight-forward to do it in core :)

**Comment by gdpelican** [comment]
Ah, it did actually behave this way (adding members directly) at one point; we've changed it because we had a wave of complaints of folks being added to groups they had no interest in being a part of, and sometimes being disoriented by a ton of unread content which they may not have signed up for or have any interest in, especially when it's not immediately obvious where all this new stuff came from. If it were to go in core, it would need to depend on an ENV which defaulted to 'off' to allow us to keep the existing functionality.

We also used to have 'how do people join' for all groups as well, which was removed in the interest of making approaching creating a group have less steps. I don't have strong feelings against that one as an option under advanced settings; @rdbartlett might be able to better speak to why it was taken out, but that one I'm more amenable to being an always on option.
