### ISSUE TITLE
Completely Disable / Remove Angular UI?

### ISSUE THREAD

**Issue by gordonrs** [loomio/loomio#3192]
Hey folks, I'm wondering if it's possible to completely disable or remove the Angular UI without much pain for our own install? We really don't want to have to deal with the additional headache of anything to do with Node at all in any part of our system. I know we can disable per user, so that's not what I'm asking.

Is this something that the devs have considered for folks with their own install, making the Angular UI completely optional?

**Comment by robguthrie** [comment]
Hi Gordon. We're just days away from completely removing the Rails MVC
based interface, so that we can move more quickly with the Angular UI. If
it's a system admin hassle then I would recommend you use the docker
container based deployment approach outlined in loomio/loomio-deploy. All
the dependencies are managed you you in this case. I would appreciate it if
you could let me know how you go using that.

**Comment by gordonrs** [comment]
Hi Rob, thanks for getting back to me.

Sorry to hear you folks are getting rid of the Rails MVC interface, that's unfortunate. It's not so much an administration hassle as it is a potential security and auditing nightmare, not to mention a PITA to debug when something goes wrong. Considering that I have what some might term extreme requirements on that front due to it being used for a political party, I have no choice but to fork Loomio to meet those requirements.

Thank you again for your reply.
