### ISSUE TITLE
exceptions on angular

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3211]
hi there, i've been busy so we got behind on pulling changes :(

we're getting angular exceptions on the console while using the new gui, for instance "TypeError: $scope.translation is undefined" or "LoomioApp exception: Error: [$compile:tplrt] Template for directive 'startMenuOption' must have exactly one root element. generated/components/start_menu/start_menu_option.html"

we ran `npm install` and `gulp compile` from the angular/ directory, is something missing?

we're trying from master without our changes too

**Comment by gdpelican** [comment]
Hey @fauno would you be willing to point me to the repo you're using if it's open source? I can see where those errors would be thrown, but without knowing what changes you have in there it'll be difficult to diagnose.

**Comment by fauno** [comment]
sure, it's https://github.com/piratas-ar/loomio, the piratas branch has our changes but the master follows yours

**Comment by gdpelican** [comment]
I'm going to take a quick peek at this tonight. <3

**Comment by gdpelican** [comment]
Hm, I've had a spin with this, and can't seem to reproduce the errors you're describing.

The 'template for directive startMenuOption' error would come about if the template in `angular/core/components/start_menu_option/start_menu_option.haml` were modified to have a pair of elements at the root, rather than the `%button`:
```
%button.start-menu__options
  .more-stuff
%div.some-other-element <-- bad!
```

`$scope.translation is undefined` would come about in `angular/core/components/translation/translation.coffee`, if there were an element somewhere which didn't define a field, like
```
%translation{translation: "translation", field: ""} <-- bad!
```

The only disparity I noticed in my setup was that the `marked.js` entry in `angular/tasks/config/vendor.yml` has been changed to be a flat file structure (`marked/lib/marked.js`, rather than `angular-marked/node_modules/marked/lib/marked.js`), which makes me suspect you've run `npm install` with node 5+, which isn't officially supported at the moment [it's in the category of 'it probably works?'] We officially run with node 4.2.6, until we're ready to make the leap to the flat `node_modules` structure in Node 5.

**Comment by gdpelican** [comment]
Closing this for now, but do let me know your experience; I want to keep third party installs like yourself as happy as possible as we move toward all angular, all the time.

**Comment by fauno** [comment]
i'll try with nodejs 4, thanks!

-- 
 D
