### ISSUE TITLE
reply by email comment showing quoted text

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3235]
Example here:

https://www.loomio.org/d/bHflPwtR/comment/984372

**Comment by mhjb** [comment]
Loomio needs to see two dashes on a line by themselves to know that a signature is coming up and strip it out.

**Comment by gdpelican** [comment]
Can this be closed with the thread mailer being merged?

**Comment by robguthrie** [comment]
Nope. We've not addressed that actually - Promise broken, sorry.

There are 2 things we can do to solve this problem and we need to think about employing both of them.

There is a feature in griddler that cuts off an inbound email where it sees a string (which is modifiable) "---- REPLY ABOVE THIS LINE----" But that's not ideal, because that would result in us needing to put that ugly string at the top of emails. It would also leave a little bit of garbage in the comment (specifically the "On Sunday, blabla James Kiesel wrote: " bit)

The other approach available is to add to the array of regexes that are used to find 'quoting' strings that various email clients use to say "This is where the copy of the original email begins" and I think my preferred option is to expand that list as we get more bug reports... 

Actually the best thing would be if we can detect the 'replied to your comment in' 'commented in' stiff that the thread mailer puts in.. but if we can make it a tiny bit more unique I'd feel more confident we're not going to get false positive matches. 

Would be good to have a conversation about this to throw around a couple of ideas.

**Comment by HSalmon** [comment]
@robguthrie, can this conversation be had soon d'you reckon?

**Comment by gdpelican** [comment]
I believe this is fixed with Rob's griddler upgrades to our email delimiters. Reopen if I'm wrong?

**Comment by robguthrie** [comment]
it's fixed good!
