### ISSUE TITLE
Subdomains not working properly

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3287]
E.g. http://osos.loomio.org shows Unread Threads (when logged in) and the front page (when logged out); instead of http://loomio.org/g/BTGpMoFH/open-source-open-society

**Comment by gdpelican** [comment]
As far as I can tell, this is a problem only for the root '/' path, and I believe it's because `routes.rb` has the `root to: 'root#index'` above the line with our `GroupSubdomainConstraints` (line 163). 

I hypothesize that moving that constraints line above the root line will fix this; would you care to test that hypothesis @HSalmon? You may need to deploy to clone to test, but this would be a real nice thing to have a protractor around.

**Comment by HSalmon** [comment]
@gdpelican, what would that protractor test look like?

**Comment by gdpelican** [comment]
My guess would be

```
@group = create(:group, subdomain: 'brainz')
browser.get('http://branz.localhost:3000/')
expectText('.group-theme__name', @group.name)
```

^^ (NB this is a very bizarre mix of Ruby and Coffee that won't work as
written)

**Comment by mhjb** [comment]
A Plus customer has reported this to me today too…

**Comment by HSalmon** [comment]
Should be fixed!

**Comment by mhjb** [comment]
That's wonderful!
