### ISSUE TITLE
Double email notification for proposal closing soon

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3362]
![image](https://cloud.githubusercontent.com/assets/1380991/15200454/1604c04e-183b-11e6-94b7-85d864e77904.png)

**Comment by gdpelican** [comment]
I'm pretty 99% sure this is because of the recent refactor to the ProposalsClosingSoonJob, which is, for some reason, publishing multiple `motion_closing_soon` events for the same motion.

Any ideas on this, @robguthrie ? It's also causing folks to get multiple notifications and multiple slack messages. so would like to get fixed if possible.

**Comment by gdpelican** [comment]
#3366

**Comment by robguthrie** [comment]
i agree it's likely because of the job. I don't understand why though.
