### ISSUE TITLE
Emailing all group members

### ISSUE THREAD

**Issue by Scumboni** [loomio/loomio#3407]
As a subgoup co-ordinator I would like occasionally to email all subgroup members. I was able to do this before 1.0, have I missed something about this feature being discontinued or am I just looking in the wrong place? Cheers - Sion

**Comment by gdpelican** [comment]
Hey @Scumboni , we've pulled this feature from 1.0 due to some feedback that not all group members wish to share their email addresses with all coordinators (or other group members)

I'm personally a fan of letting the coordinators specify whether member email addresses are shared with other members on the memberships page, and would be happy to support a PR in that direction.

**Comment by Scumboni** [comment]
Thanks for the clarification!

We would certainly find it useful for coordinators to be able to message members, without starting a discussion thread.
