### ISSUE TITLE
Threads sometimes unmute themselves

### ISSUE THREAD

**Issue by alannallama** [loomio/loomio#3408]
Occasionally, all the threads I've previously muted seem to suddenly unmute themselves. I mute them again, and then a few weeks later it happens again and they're all suddenly in my unread list (and not showing in my muted threads list). This just happened right now, and has happened before a few times in the past.

**Comment by gdpelican** [comment]
Hey @alannallama I'm trying to process this feedback some and have realized that it's similar to several issues on here which fall into a 'this thing happened sometimes, and it sucks, but I don't know what's going on.'

This leaves it in the awkward position of 'it's a problem, but I can't work on it.' Which means it sits in the issues list forever and while I hear about it a lot and know about it, it never gets to the point of 'hey I'll fix this', because there's this giant and unreconcilable upfront cost to figuring out what's going on without enough information. I give these a 5 minute look, and if there's not immediately obvious to me what's going on, I don't spend more time on it than that (because the time required might be several hours or days, who knows?)

I'm not saying you're not giving enough information, but I am saying that there should be some form of process improvement here, because there's a disconnect here between how much info you have (or are able to) provide, and how much we need in order to fix the thing. So I'm wondering if this could go into the feedback pipeline, as a thing to prioritize fixing, in the interest of getting the github issues list more towards 'a list of things devs can work on'? I'm also open to other suggestions, but would rather not let this kinda thing sit for months like the others have.

Things that allow me to fix things that are bugs:
- Ids of specific discussions / groups / whatever in production which are misbehaving
- Step-by-step reproduction steps that can be performed on loomioclone to reproduce the bug
- A screenshot of the javascript console after the thing occurred (<-- this is more for 'this thing didn't work', rather than 'I had a weird thing happen')
