### ISSUE TITLE
license statements and AGPL clarification

### ISSUE THREAD

**Issue by cmhobbs** [loomio/loomio#3413]
Hello, Loomio Team!

I approved an entry for your project on the Free Software Directory (listed here:  http://directory.fsf.org/wiki/Loomio).  It has been brought to my attention through that channel that there were a couple of discrepancies with your license statements:

1.  Copyright and license statements should be placed at the top of each of your source files.

2.  You should clarify if your projects is AGPLv3-only or if you intend to license it as AGPLv3 or any later version.

This document may help guide you:  http://www.gnu.org/licenses/gpl-howto.en.html

Thank you so much for contributing Free Software and thanks for producing Loomio!

**Comment by gdpelican** [comment]
Hm, do any of the original license-deciders have thoughts on this? My thoughts are

a) I don't have any desire to change the license of the software at this time
b) I don't have any desire to add hundreds of copyright statements into our source code

I know those two things are in conflict, and am curious what the other shareholders think.

@robguthrie @rdbartlett @alannallama

**Comment by rdbartlett** [comment]
Thanks for flagging this @cmhobbs. 

Adding a line to every single file strikes me as onerous and bloaty. I was under the impression that the [license.txt](https://github.com/loomio/loomio/blob/master/LICENSE.txt) file in the root directory provided coverage for the whole app.

I'm guessing I'm not the only one who is operating on that assumption - do you know if there is legal precedent for that assumption being tested in any jurisdiction?

**Comment by joshuagay** [comment]
Hi, I collaborate with @cmhobbs on updating directory.fsf.org and I'm also the licensing & compliance manager at the FSF, so I figured I would jump in on this thread and offer any support that I can. Thank you for developing Loomio and releasing it as free software under the terms of the GNU AGPL version 3, and  thank you for taking the time in considering our suggestions. I wan tto emphasize that these are just suggestions based on general best practices we think all free software projects should adopt, we have n legal authority to dictate how you go about licensing, and we are not trying to offer you legal advice.  If at the end of this thread, you reject all our suggestions, then we respect that choice and we will continue to list Loomio on directory.fsf.org and make sure the public is aware that it is useful free software. But hopefully we will be able to offer at least some useful changes you will consider making. 

So here are the big points I hope you will consider when licensing Loomio:

- In general, we think it is best for everyone if you place a copyright and license notice on each nontrivial source file. There are a lot of reasons why we recommend this, but one reason is that if the source file is used elsewhere (i.e., outside of Loomio), then this will help make sure that the license info carries with that source file and it doesn't become disconnected. A general template for this which you can adapt to meet your needs can be found at the bottom of the AGPL in the section *How to Apply These Terms to Your New Programs*.
 
- It's better to have such notices in some places rather than in no place at all. Even if you reject the idea of putting a notice on all nontrivial source files, I hope you will at least consider putting a proper notice in the README file and also consider putting it at the top of the "main" entry points of the program. 

- Lastly, I'm not sure if Loomio itself generates a license notice and an offer of source, but, it is something you should also consider. Section 15 of the AGPL states that those using modified versions of Loomio must "prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software." However, if they are running Loomio unmodified then the only way a user would get such an offer is if you all have added on the begin with. 

I'm happy to help with some finer points if you would like. Also, the FSF offers a general service to all free software projects. Simply email licensing@fsf.org anytime if you have questions about free software licensing. 

Best,

Josh

**Comment by cmhobbs** [comment]
Hi, @rdbartlett!

After re-reading my PR, it sounds a little too heavy handed.  I was in a hurry and didn't take the time to provide enough information.  I apologize for that.  @joshuagay covered the issue much more clearly than I did.

Thanks again for Loomio!

cmh

**Comment by robguthrie** [comment]
Thanks for contacting us. At this stage we'll pass on adding license information to each file, it just sounds a bit un fun. 

We do link to this github repo from the front page. Which I think is pretty prominent.

I see @gdpelican has added a link to the LICENCE.txt from the README.md so I think we're ok now.

**Comment by cmhobbs** [comment]
Thanks for taking the time to work through this with us and once again, thanks for Loomio!

**Comment by strypey** [comment]
FYI it was me who submitted the Loomio entry to the FSD. Just stumbled across this old thread while updating the description and version information.

@cmhobbs when you say:

> Copyright and license statements should be placed at the top of each of your source files.

I assume we're talking about adding the name of the license (with or without an "or later") and a URL for the Loomio license.txt file, not the whole text of the license?

@robguthrie 
> At this stage we'll pass on adding license information to each file, it just sounds a bit un fun.

I totally understand. Maybe this is something the likes of me could be charged with doing, thus challenging me to put my mouse where my mouth is ;) But I do wonder, is there a way to automate it, so that no human has to do a repetitive, un fun job that a computer could do much quicker?

> We do link to this github repo from the front page.

Does that include the account creation page, in case someone sets up an account using a URL someone else has sent them (eg as an invite generated within the app)? If so, I think that's totally adequate to cover the third bullet point in the list @joshuagay posted.
