### ISSUE TITLE
Prefer user language not set in different devises

### ISSUE THREAD

**Issue by natiloomio** [loomio/loomio#3528]
Some users have reported that even if they use a different language when they open Loomio in a different devise it's in English.
I check with my phone and I have experienced this issue when trying to log in through my Home screen shortcut. Or trying to access Loomio through /Inbox or through the "see it on Loomio" link from an email. 
The Profile page is the only one in my prefer language and when after visiting it I navigate to any other page my prefer language is set again (without having to click update profile).

But it works normally while doing the log in through searching for Loomio.org on my browser.
I use Firefox on Android.

**Comment by robguthrie** [comment]
Mind if I tidy this up?

When signed in as a user with a selected locale of Spanish, but a browser that defaults to English.

Visiting loomio via https://www.loomio.org/inbox or a discussion link results in Loomio displaying the page in English rather than Spanish.

I'm unable to reproduce the bug with these steps. @natiloomio is the problem happening all the time or just sometimes?

**Comment by natiloomio** [comment]
it happens all the time in my phone.

**Comment by robguthrie** [comment]
Nati and I just sat down together and refined the bug statement.

If I use a english browser to view a thread (or any other in-app page), then I login with the in-app form, the app does not switch to the current users locale (spanish). 

Reloading the page fixes this problem.

recommendation for solution:
When you login from inside the add, the app needs to reload the translations according to the users' locale.
