### ISSUE TITLE
On thread page, when I select invite people from FAB, this group should be selected

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3549]
Currently it is just selecting the first group in my groups list.

**Comment by gdpelican** [comment]
Just marking this as a 'feature', since it's never behaved that way. There's several things I want to do to make the FAB actions behave more intuitively.

**Comment by HSalmon** [comment]
@gdpelican, does this mean you think this should be a bigger job than just this one improvement?

**Comment by gdpelican** [comment]
I'd be happy to just knock this one off, but there's an architecture question in my head around how we want to best handle this.

We've been running into some situations recently (like 'how do I tell which group to highlight in the sidebar', or 'should I display this plugin which only appears for some groups?'), which point to the need for storing what the 'current group', and/or 'current thread' is in the application state. This is another one of those things where we have this idea of 'what group am I currently interacting with? What thread?', and it's the same whether you're on the memberships page, the previous proposals page, etc.

We've skirted with this idea some, but it's not fully realised yet. The simplest implementation is this:

- Everytime we visit a new page, we broadcast 'current component', along with some info about the page. (this works today)
- When we broadcast that information, we could pass the group / thread through with it

```
$rootScope.broadcast 'currentComponent', {page: 'threadPage', group: @discussion.group(), discussion: @discussion}
```
if a page isn't particularly associated with a group, then we don't pass that info
```
$rootScope.broadcast 'currentComponent', {page: 'dashboardPage'}
```

Then, when we listen for the broadcast, we set the current group on the AppConfig

```
$scope.$on 'currentComponent', (data) ->
  AppConfig.currentGroup = data.group.id
```

Which means that the FAB can access that info when trying to determine which thing to preselect when opening the modal

```
ModalOpen ThreadForm, discussion: -> Records.discussions.build(groupId: AppConfig.currentGroupId)
```

So that's the idea... I'm just 100% on wanting to implement it yet.

**Comment by rdbartlett** [comment]
Sounds great James. I'll put it on the Groomers agenda. I agree with your
sense that it's not top priority.

**Comment by robguthrie** [comment]
Sounds good to me. Did a quick mental walk though an alternative where we broadcast 'currentGroup' but that gets dumb when you navigate to components that don't specify a group, like user settings. I like what you've suggested because it explicitly clears currentGroup if you navigate away from a group context.

**Comment by HSalmon** [comment]
Isn't most of what you've proposed (passing the group / thread through when we broadcast currentComponent) basically what we'd need to implement anyway to fix this problem? Is it worth just implementing this now if that's the case?

**Comment by HSalmon** [comment]
Is the section on **Binding to a getter/setter** in the ng-model documentation of any relevance @gdpelican: https://docs.angularjs.org/api/ng/directive/ngModel

**Comment by gdpelican** [comment]
If you want to have a stab at implementing it, that'd be okay with me (I'd merge it), but like I said I'm not 100% sold on it being the right way to go, since it will lead to us having more stuff in a global application state, which we've managed to avoid pretty well so far.

Not quite following the ng-model option; what's the proposal there?

**Comment by HSalmon** [comment]
I'm having a little trouble implementing this. Maybe we could pair @gdpelican?
