### ISSUE TITLE
Welcome modal showing up inappropriately

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3573]
As a logged in long-time Loomio user on Chrome / OS X I just joined [a group](https://www.loomio.org/g/yzZ0vIpf/conet) via their [shareable link](https://www.loomio.org/invitations/4638c0bbab75ffd09e63) (they're sharing it with the public, so no privacy concern here), and I was shown the Welcome to Loomio modal. Which doesn't seem right. I was expecting to see that only once in my Loomio lifetime.

![image](https://cloud.githubusercontent.com/assets/1380991/17387068/674c90a8-5a44-11e6-89d0-17e1d105ce19.png)

I can reproduce the problem by leaving the group, then visiting the shareable link again.

I've attempted to follow the new draft bug reporting guidelines on this one.

**Comment by gdpelican** [comment]
I see this as a feature request because this is working as designed. The relevant logic:

```
Show the group welcome modal
  if the group is a parent group
  and I'm a member
  and I haven't seen the welcome modal for that group before
```

Two ways to go here:

- Make this modal appear only once for each user (ie, change that last line from 'I haven't seen the welcome modal for that group before' to 'I haven't seen the welcome modal ever.')
- Change the messaging on the modal to make it more like you're being welcomed to that community, rather than the tool itself.

**Comment by robguthrie** [comment]
nice one james. I experienced this today and felt it should be once per user
