### ISSUE TITLE
Handle loading large datasets / pagination correctly

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3623]
For instance (and to reproduce do this):
- visit [Workers' previous proposals](https://www.loomio.org/g/T9ZtzNcD/previous_proposals)
- search for "I've shared an outcome I want to get from today's meeting"
- click the heading once to open it
- click again, the address bar url will change to https://www.loomio.org/proposal/aHE5jYOS (an invalid url; it's missing d/……/

**Comment by mhjb** [comment]
I say 'sometimes' because more recent proposals do have their proper full url

**Comment by gdpelican** [comment]
This is related to the pagination thing as well; it's because that proposal has been loaded without a discussion from elsewhere in the app (like, it's on your dashboard, or in your notifications), so it doesn't know what key to put in `d/:key/proposal/:proposal_key`.

Long story short we haven't quite gotten pagination nailed yet.

**Comment by gdpelican** [comment]
Also referenced in #3622 #3620

**Comment by gdpelican** [comment]
We have a nice pagination solution in now; happy to hear about individual issues with pagination as they arrive
