### ISSUE TITLE
Changing subject line for "Yesterday on Loomio" email"

### ISSUE THREAD

**Issue by finnlewis** [loomio/loomio#3683]
Hello!

we're enjoying self hosted Loomio instance, but would like to distinguish emails from our self hosted Loomio and Loomio.org by changing the subject line of the reminder emails.

I see this file https://github.com/loomio/loomio/blob/master/config/locales/server.en.yml appears to set variables for emails, including subject lines.

If we want to override this, what is the best way to do so while allowing future upgrades to respect any custom changes?

Many thanks,

Finn

**Comment by robguthrie** [comment]
Hi Finn,

in `app/mailers/user_mailer.rb` you can see a [`def missed_yesterday`](https://github.com/loomio/loomio/blob/master/app/mailers/user_mailer.rb#L6) where we prepare the email to be sent.

We call `send_single_mail` and pass `subject_key`. Maybe the thing to do is to add a `subject_params` as on [line 35](https://github.com/loomio/loomio/blob/master/app/mailers/user_mailer.rb#L35) with a key of name and a value of ENV['CANONICAL_HOST'] (or we could think about introducing another environment variable that represents the site name rather than the hostname, think Loomio rather than www.loomio.org).

Then within the string in server.en.yml you need to add `%{name}` into the string for that variable to be interpolated.

Finally you can test out your changes if you have a development environment setup, by visiting `http://localhost:3000/rails/mailers` where you can preview mailers.

Hope that helps.
