### ISSUE TITLE
Lintel hangs around inappropriately

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#3718]
When I visit a thread with unread content, I'm scrolled to the bottom, and the lintel shows up. If I click it, I'm scrolled to the top and the lintel disappears, as it ought to. If I just scroll to the top, however, the lintel doesn't disappear:

![image](https://cloud.githubusercontent.com/assets/1380991/18534361/413aedc2-7b3e-11e6-9f5b-5196bf579638.png)

**Comment by gdpelican** [comment]
Can't repro this one. Any mitigating circumstances I should be aware of? Does it happen all the time?

**Comment by mhjb** [comment]
Not 100% of the time. It does happen more 'reliably' with these steps:
* visit thread with unread content

**Comment by gdpelican** [comment]
Cool, I've got that happening for me now. Looks like 'keyboard up arrow' and 'scroll' are different events, which aren't triggering the digest loop, which means the page doesn't know it's scrolled itself.

It'd be interesting to see if we have unread issues because people are using up/down arrow instead of scrolling too. Anyway I'll try to fix this one.
