### ISSUE TITLE
Mentioning a user while replying to them does not highlight the mention

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#3776]
![image](https://cloud.githubusercontent.com/assets/970124/19288403/5b02228c-9062-11e6-9a47-aa241542c985.png)

I'm concerned this might give the impression the user has not been mentioned.

**Comment by rdbartlett** [comment]
Oh, this might be plugin related, I've only seen it on Enspiral, then tested on Loomio Community on clone

**Comment by gdpelican** [comment]
Repro steps:

- Mention a user

Expected: The user's username is highlighted as a mention, but they do not receive a notification (because they'll already receive a notification for having their comment replied to)
Actual: The user does not receive an additional notification, but their username is not highlighted in the reply.

**Comment by rdbartlett** [comment]
thank for spelling out the detail James, that helps :)

**Comment by gdpelican** [comment]
#3777

**Comment by gdpelican** [comment]
Fixed pending deploy
