### ISSUE TITLE
Incorrect comment author when replying by e-mail with other To's and Cc's.

### ISSUE THREAD

**Issue by uportalis** [loomio/loomio#3945]
Scenario:
1. User A and User B are members of the group "LoomioGroup".
1. User B creates a new discussion on LoomioGroup.
1. User A receives an e-mail notification for the creation of a new discussion.
1. User A reply by e-mail, adding User B in the "Cc:" field before sending the e-mail (i.e. To: LoomioGroup / Cc: User B).
1. Comment is OK on Loomio (author is "User A").
1. User B receives one e-mail from Loomio (notification of the new comment) AND another e-mail from User A.
1. User B reply to the second e-mail. So, that reply is "To: User A ; Loomio".
1. Comment is NOT OK on Loomio. Author is "User A" while is should be "User B".

P.S.: I don't know if there could be a better minimal scenario.

**Comment by gdpelican** [comment]
Hm... I think forwarding Loomio emails will likely always get one in trouble; those emails have the ability to respond as the user 'baked' into them (you can't do anything else with them; IE log in or change a password or view content, but you can create comments in a discussion if you have access to a thread email.)

A potential fix here might be to check the sender email address against the user we load up from the email, but I am _very_ hesitant to go that route because it will also prevent legitimate users from replying via email, if they have email forwarding setup or whatnot.

**Comment by fauno** [comment]
maybe check the pair to + in-reply-to?  the to address can be reused but
the in-reply-to would likely change.  of course this would prevent
accidentally posting as someone else, not someone trying to impersonate
a comment.

i wanted to take a look at this so loomio email notifications are
threaded too...
