### ISSUE TITLE
'cover photo' feature is in need of some love and care...- no?

### ISSUE THREAD

**Issue by zblace** [loomio/loomio#3977]
There is almost no control of display and positioning of cover pics!  :-(

Also it would be awesome if they do not post-process it and distort otherwise clear .png graphics uploaded into that blurry mess we see now on display :-/

**Comment by gdpelican** [comment]
PRs are more than welcome in this area, but it's not on our immediate roadmap (we're focusing on the experience _outside_ of a Loomio group at the moment)

**Comment by zblace** [comment]
What is experience outside of the group in practice?

**Comment by gdpelican** [comment]
Sorry for not responding to this earlier, @zblace .

We've been working on a whole bunch of new decision types (finding a meeting time, single/multiple choice polling, dot voting, and yes/no questions), all of which will be able to be created outside of a group (because we've found it's too hard to get started if you need to make a group, start a discussion, and _then_ make a decision. We're decisionmaking software, you should be able to make a decision instantly with this thing.)

The other piece of this is a bunch of work around sharing polls in places where users are... putting a shareable link into an email chain, posting into slack and facebook, embedding polls in webpages using JS, etc. You can check out `loomio.org/p/new` to try out the new flows.

In response to the cover photo thing, I agree that it's not ideal, and would love for someone to step up and either write these features in (as you note, users expect _way_ more control over the media you put up on your pages than when we first wrote this a couple years ago), or throw in a library that does this better than we've coded it.... but for now I have to leave it because we're stretched real thin on dev resourcing.

**Comment by zblace** [comment]
​Thank you for elaborating on priorities.
I agree that is good choice and direction.
Looking forwrad to ​see you move from only
in-site decision making into sherable applets/services.

best Z
