### ISSUE TITLE
Can't see edit history of context box anymore

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4050]
The Edited link seems to have fallen off

![image](https://cloud.githubusercontent.com/assets/1380991/25609524/a9b6821e-2f73-11e7-9d33-387a49cd20fe.png)

**Comment by gdpelican** [comment]
Yes sorry I should have been more transparent about this. The 'edited' modal was quite broken by the material upgrade, and I've hidden it for now. It will reappear soon.

**Comment by gdpelican** [comment]
Also that feature desperately needs some love if we're going to keep it

**Comment by juliencarnot** [comment]
The show edit history button on comments works pretty well:
![image](https://user-images.githubusercontent.com/3848493/35267652-45ce1084-0027-11e8-8c16-35c34093da60.png)

but it is missing for discussion context. On the other hand, the information that an edit was made appears in the thread for contexts but not for comment. 

I feel the "show edit history" button could be added to the discussion tools and to the polls tools for details box. 

Of course, displaying a nice graphic diff (as [gitbook does](https://github.com/GitbookIO/react-rich-diff)) would be even better, but the edited modal as it is for comments will already help groups working more transparently.

**Comment by gdpelican** [comment]
I am not happy with our view history functionality, and want to, when it
comes up, dedicate some effort to making it better. The discussion one was
removed because it had miserable performance and presented a confusing and
long list of changes that were often impossible to parse. Because polls and
discussions tend to have longer contexts that change more often, the
equivalent experience for them is not something that's acceptable for me to
have in the app (the comment history experience is only barely so).

Discourse (which has copied StackOverflow I believe) is the target
functionality here, which displays a nice diff and navigates between
separate edits.

On the other hand, we almost never hear about this feature (neither 'we
want it', or 'it sucks') from customers, so I've been happy to bury my head
in the sand about how subpar this experience is for the time being. I'd be
more than happy to look at a PR around this, with a minimum improvement of
displaying a list of diffs more nicely using some library (cursorily [this](
https://github.com/amweiss/angular-diff-match-patch) or [this](
https://github.com/hipster-labs/angular-object-diff))

**Comment by juliencarnot** [comment]
Ok, thanks for the explanation and pointers. I'll see if I can get something to work and in that case I'll submit a PR, in the meantime if somebody else want to give it a try, please do!

**Comment by gdpelican** [comment]
Alright, we have deployed a much better iteration of this feature now. 🗡
