### ISSUE TITLE
Duplicate memberships

### ISSUE THREAD

**Issue by modulistic** [loomio/loomio#4068]
I am seeing duplicate memberships in some groups on our [own instance of Loomio](https://github.com/loomio/loomio-deploy).

I am a bit puzzled because I figured out a constraint would be missing in the model but I found [this is not the case](https://github.com/loomio/loomio/blob/0b7faacc9b87814c4cd21e3a47c7d87dde0a7a49/app/models/membership.rb#L7).

But in spite of this constraint I see duplicate memberships on some groups (not just duplicate rows on the database table, but the group count matches and I see the avatars on the members box); and it is quite easy to reproduce, it just takes two admins to click the "approve" button.

```
select user_id, group_id, count(*) from memberships
  group by user_id, group_id
  having count(*)>1
  order by group_id, user_id;
```
```
 user_id | group_id | count 
---------+----------+-------
      21 |        3 |     2
      46 |        3 |     2
      31 |        8 |     2
      26 |        9 |     2
      46 |        9 |     2
      21 |       12 |     2
      38 |       12 |     2
       9 |       13 |     2
[...]
      46 |       13 |     2
      47 |       13 |     2
(16 rows)
```

**Comment by gdpelican** [comment]
@robguthrie a cursory glance here makes me suspicious of this line in `group.rb`:

```
  def add_member!(user, inviter=nil)
    begin
      tap(&:save!).memberships.find_or_create_by(user: user) { |m| m.inviter = inviter }
    rescue ActiveRecord::RecordNotUnique
      retry # <-- why do this?
    end
  end
```

any insights into why that's there, and if we can drop it? I reckon the `find_or_create_by` should make the rest of this pretty airtight.

**Comment by robguthrie** [comment]
I can't explain it either.

RecordNotUnique... on membership.. which does not have a key or sequence_id which are the two fields that might warrant that kind of work around.

I'm happy to remove it and eat that exception if it happens.

**Comment by robguthrie** [comment]
Oh. Now I see. Sorry, I had not seen the first comment.

We slipped up with the schema, and did not add a db unique constraint on user_id, group_id when we started the table. Now it's going to take a clean up migration to get there. That RecordNotUnique line is not going to help anyone

**Comment by alannallama** [comment]
Not sure if this is the same issue or a different one.... I've got two versions of Cath in my group, even though she's only been invited and signed up under one email.

<img width="629" alt="screen shot 2017-05-11 at 1 09 26 pm" src="https://cloud.githubusercontent.com/assets/5498878/25927632/54e543b8-364b-11e7-8043-0ff618b22e80.png">

<img width="379" alt="screen shot 2017-05-11 at 1 09 54 pm" src="https://cloud.githubusercontent.com/assets/5498878/25927643/6bf1c374-364b-11e7-873e-de5f37543f07.png">

Realised this because I tagged her in a participation request and she came back saying she'd already participated (oops!)

**Comment by gdpelican** [comment]
This is a different issue. That Cath is voting as a visitor, instead of logging in. We've hopefully addressed that one by marking polls in a group 'anyone can participate: false' by default.

We'll want to write a migration to remove duplicate memberships and slap a unique [user_id, group_id] index on the memberships table. I'll also take out that retry line when I get to this.

**Comment by gdpelican** [comment]
We have a unique constraint on this now, so this issue shouldn't occur in the future.
