### ISSUE TITLE
Current Node Version

### ISSUE THREAD

**Issue by GenericUK** [loomio/loomio#4073]
I am trying to establish which version of Node is current.

There is a reference by @gdpelican here https://github.com/loomio/loomio/issues/3938 that says we should be using v7.4.0, this is also the version in the https://github.com/loomio/loomio/blob/master/angular/package.json , however https://github.com/loomio/loomio/blob/master/.nvmrc still forces NVM to 4.2.6, Install instructions here https://github.com/loomio/loomio/blob/478cbd5364e971cb8732fcd97c4a2dcdb6d0dcf7/docs/en/development_handbook/quickstart.md also say 4.2.6, but environment setup here https://github.com/loomio/loomio/blob/478cbd5364e971cb8732fcd97c4a2dcdb6d0dcf7/docs/en/development_handbook/setup_environment.md says 4.4.5

I have test installed with 4.2.6 and 7.4.0, I am currently persevering with 7.4.0. These are the issues I had to resolve.

1. grunt & grunt-cli unmet dependencies, so I just installed them after
2. graceful-fs v3.0.0 and before will fail on node releases >= v7.0

**Comment by fauno** [comment]
fwiw we've been using 4.8.0 from nvm

-- 
https://endefensadelsl.org/

**Comment by gdpelican** [comment]
Sorry for the delayed response here.

We've specified Node 7.4.0 in the 'engines' field of our package.json, which should be the canonical source of truth for the node version. I'll update those references in the docs and .nvmrc though, thank you for pointing out the inconsistencies.

The grunt dependencies are because we're trundling along with an old version of `ng-file-upload`, a version which had placed those grunt deps in `dependencies` rather than `devDependencies`. I would _love_ for someone to come along and upgrade us to a less ancient version of this package, but it Works For Now and I haven't been able to prioritize fixing it.

Not sure about the graceful-fs one, sorry.

**Comment by GenericUK** [comment]
Cool! Thanks for the update.

Whilst on the node topic, shouldn't the .nvmrc be in /angular? Isn't node only used for compile and development/test. Also for gulp compile to use .nvmrc doesn't it require nvm exec?
