### ISSUE TITLE
Create a 'Deploy to Heroku' Button

### ISSUE THREAD

**Issue by spencerthayer** [loomio/loomio#4074]
It would be super useful if we could get a `Deploy to Heroku` button which would enable users to easily deploy Loomio to a Heroku instance without ever leaving the web browser. And with just a little configuration on the users end they'll have something running almost instantly.

I propose the button because it is ideal for communities who need to make decisions quickly with the flexibility of something like Heroku.

More about Heroku deploy buttons here, https://devcenter.heroku.com/articles/heroku-button .

**Comment by robguthrie** [comment]
Hi Spencer, thanks for the suggestion.

If someone does not know how to deploy to Heroku, how are they going to maintain the system, setup DNS, SMTP etc?

People can setup Loomio groups instantly on loomio.org and we'll maintain things and keep them running. It's also beneficial to us because they get prompted to pay, so we can afford to keep development going on the product.

Can you describe why loomio.org hosting is not suitable for such groups who can't set up this stuff anyway?
