### ISSUE TITLE
Remove CDN calls and other remote third-party libraries

### ISSUE THREAD

**Issue by FramaJosephK** [loomio/loomio#4087]
For privacy (avoid tracking) and security reason ([data leak](https://techcrunch.com/2017/02/23/major-cloudflare-bug-leaked-sensitive-data-from-customers-websites/)), it would be better if third-party libraries were called locally. I found this librairies in the code:

- Google Fonts ([Material icons](https://github.com/loomio/loomio/blob/master/app/views/layouts/angular.html.haml#L18) and [Open Sans](https://github.com/loomio/loomio/blob/master/app/views/layouts/application.html.haml#L8))
- [Youtube videos](https://github.com/loomio/loomio/blob/master/angular/core/services/user_help_service.coffee#L17) (yes, youtube is a tracker : there are stats on each video :) )
- [Google Analytics](https://github.com/loomio/loomio/blob/master/app/views/layouts/application.html.haml#L13) (is it disabled by default ?)
- Cloudflare ([Marked.js](https://github.com/loomio/loomio/blob/master/app/views/help/markdown.html.erb#L33), [jQuery](https://github.com/loomio/loomio/blob/master/app/views/layouts/pages.html.haml#L30), [Font Awesome](https://github.com/loomio/loomio/blob/master/app/views/layouts/pages.html.haml#L28))
- [Gravatar](https://github.com/loomio/loomio/blob/master/angular/core/components/user_avatar/user_avatar.haml)
- …

I know that they are faster and easier to use but it's not good for users and visitors (and cleaning is tedious when we host our own Loomio instance).

Could you consider doing something about it ?

**Comment by gdpelican** [comment]
- GA is disabled unless you manually populate the GOOGLE_TAG_MANAGER_ID ENV variable
- Marked, jquery, and FA cdn calls are legacy code which are not used in the app (I think they might happen on the contact page? And the sign in forms which are going away soon.)
- Gravatar and Youtube are third party services... I'm not sure what you mean by calling them locally? (I would look at a PR which pulled the help video out into an ENV and removed it if not set though!)

That leaves the fonts which... well there's a [big long list of pros and cons](http://stackoverflow.com/questions/22116682/webfonts-or-locally-loaded-fonts) between local hosting and cdn hosting.. I lean very slightly towards the third party option because Google does some compression and browser detection stuff that I don't want to care about.
