### ISSUE TITLE
[feature] allow more votes for check polls as an option during poll creation

### ISSUE THREAD

**Issue by pravi** [loomio/loomio#4144]
For example: do you want to bring friends for RSVP?
Do you want to buy T shirt for your friend/partner?

Example poll https://www.loomio.org/p/84SYRuBe

This should be enabled when the poll is created. This way we get a more accurate number than one person one vote.

**Comment by gdpelican** [comment]
Hm, are you saying you want to be able to vote with a number rather than yes/no? Or are you suggesting custom fields which each participant fills out alongside their stance?

I wonder if we're stretching the limits of what the count is intended for and want to consider another polling type here. It smells like a TypeForm style use case, where you're defining your own fields and having folks fill them out as part of their stance.

**Comment by pravi** [comment]
Custom fields would be one option, but here its just option to increase the number of yes. Like Are you coming? If yes, are you bringing guests, yes, 3. Or Do you want T Shirt, If yes, how many do you want?
