### ISSUE TITLE
Cohorts have fallen off admin

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4206]
… cohorts needed for AAARRR dashboards

**Comment by gdpelican** [comment]
Do we need AAARRR dashboards? I don't think we're tracking them anymore. Doesn't metabase handle this for us without using cohorts?

**Comment by mhjb** [comment]
dashboards are on Metabase, but they use the cohorts table, like this:

![image](https://user-images.githubusercontent.com/1380991/28110508-c62daf7a-6746-11e7-8b1d-fb04130adbb7.png)

… and there used to be a page in the admin that would let me add new cohorts (just a auto-incrementing ID + start & end dates)

**Comment by gdpelican** [comment]
It looks like the last cohort was set up in March... are we starting them back up again?

Can you give me a little more background about what you're looking to do here? If anything, we should be automatically creating cohorts with a rake task, or not caring about them anymore.

**Comment by gdpelican** [comment]
If I expanded the current task to do the following:

- Job runs daily
- Check to see if there is an 'active' cohort (one where the end date is in the future
- If one doesn't exist, create one for a 2 week period from the end date of the last cohort
- Tag all groups created since the start of the last cohort as belonging to that cohort

Would that take care of this? I am fairly against putting anything more into the admin panel.

**Comment by mhjb** [comment]
yes!

**Comment by robguthrie** [comment]
I don't think we want to have cohort stuff in the main repo or database, and we don't use it right now anyway.

Closing as I want to cut down the number of open issues

**Comment by mhjb** [comment]
Understandable; but I'd love to be able to have cohorts working, so as to be able to see all-of-time performance at https://metabase.loomio.io/dashboard/1
