### ISSUE TITLE
change wording from Dismiss to Mark as read

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4389]
![dissmiss](https://user-images.githubusercontent.com/3848493/32406610-d0a287b6-c17b-11e7-9ace-2cf8cd44f5b3.png)

When reading this modal, I wondered if it would not be clearer if we renamed "Dismiss" to "Mark as read": it seems like a more familiar action for anybody having used a mail client, it is more consistent with the Unread menu, and feels less "dismissive" of the thread.

What do you think?

**Comment by gdpelican** [comment]
Dismiss is a slightly different action to mark as read, in that 'dismiss'
says 'Don't tell me about this thread again until there's new activity',
but it does not update your last read post number.

So, if the following happens,

- There's a discussion with 2 unread items
- You dismiss it
- Another unread item happens

It will show up with 3 unread items, rather than 1.

**Comment by juliencarnot** [comment]
Ok, I got the subtlety, but I'm not sure this is better expressed by the word dismiss. In my view, if you mark a *thread* as read and it makes sense that when you open the thread, it will show the first unread/unseen item in the thread.

By the way, do you have analytics data on what proportion of users have used this feature more than once?

**Comment by gdpelican** [comment]
Dismiss is not a heavily used feature for sure; I don't have the numbers in front of me but I'd be surprised if it's used by more than 1% of users.

However, I think it's an important feature to have, especially as we develop more features like the 'seen by count', to give users the option to make something go away _without_ reading it. (Otherwise if we  only give you the option to make something go away by reading it, we're over-representing the number of people who looked at / care about your thread.)

**Comment by robguthrie** [comment]
I'd be happy for it to be called "mark as read" and still have the same functionality, but I've not heard any other feedback about the topic and would like some more before such a change.

**Comment by gdpelican** [comment]
Closing for now
