### ISSUE TITLE
time poll icon order is reversed

### ISSUE THREAD

**Issue by robguthrie** [loomio/loomio#4424]
see this:
![image](https://user-images.githubusercontent.com/486367/33038285-ffea0948-ce98-11e7-83a4-05246dbcb9b1.png)

vs this:
![image](https://user-images.githubusercontent.com/486367/33038306-1452b24a-ce99-11e7-821b-4a68ee1ad128.png)

**Comment by BenDawes** [comment]
I've been trying to repro this to no success. Is the second image certainly the same decision as the first? Notably there are 5 responses in the second images but 7 in the first.

**Comment by gdpelican** [comment]
Yeah this is going to have something to do with how we sort responses in the meeting chart, as opposed to our matrix counts which are used in the preview square. Would be very keen for someone to come in and pick this up.

**Comment by BenDawes** [comment]
@robguthrie could you go into a bit more detail with what the issue is here? In particular what the above images _should_ look like?

**Comment by juliencarnot** [comment]
@BenDawes 
Another example on this time poll with 9 answers:
![image](https://user-images.githubusercontent.com/3848493/35035325-42e229e2-fb71-11e7-91fa-e7c84321cacd.png)

The icon in the decisions list shows the 5 last answers. It should look like a compressed version of this:
![image](https://user-images.githubusercontent.com/3848493/35035567-149befc2-fb72-11e7-9937-68a4d3a3a6e2.png)
 but it is reversed in order (last of five go first) and dates (the first date gets more votes, but is shown in last column), as if it was rotated 180° clockwise:
![image](https://user-images.githubusercontent.com/3848493/35035391-78365d7a-fb71-11e7-8e77-0a2e58bf97e5.png)

The problem is that if I just look at the icon, I get the impression the 5 last votes are the opposite of what they really were.

**Comment by gdpelican** [comment]
This should now be fixed.
