### ISSUE TITLE
I wonder what deleting an activity item means?

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4435]
![image](https://user-images.githubusercontent.com/1380991/33253437-48657c34-d3a8-11e7-871c-99a7c8fc53db.png)

**Comment by gdpelican** [comment]
We've had requests to allow coordinators to clean up their threads some... it's quite common for someone to start a thread and then go through several edits of it right away, resulting in quite a bit of 'litter' at the beginning of the thread, or whenever someone goes on an editing spree.

@robguthrie I'm quite keen to iterate beyond this feature by either grouping thread edited events or collapsing them so they don't take up so much space, because I (like @mhjb ) find the idea of 'removing' events from history a bit smelly.

So I think we'll leave as-is for now, with an eye towards improving in the future.
