### ISSUE TITLE
Screwy numbers on Check poll

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4445]
"15 out of *blank*" and "16/28": which one to believe?

![image](https://user-images.githubusercontent.com/970124/33484757-d37adcda-d68a-11e7-8056-626b0f6eaab5.png)

**Comment by gdpelican** [comment]
Thanks. This seems like something a contributor could do a really good job with if we don't get to it first.

**Comment by BenDawes** [comment]
I have a fix for the missing value after 'out of' @gdpelican . However I'm not sure what we want the correct value to be. It's my belief that in the above example, 16 people HAVE responded, and 15 of them HAVE responded with a Tick (the other 1 with a Cross).

The current (buggy) code for the string after 'out of', if it were correct, would in the above example put '15 out of 28'. However, is there a strong case that it should be '15 out of 16', since 15 out of 28 might give the erroneous impression that that is the final result.

Shall we go with (X out of Y) where X is number of Tick responses and Y is total responses so far, or the current idea of Y is total members involved in the poll?

**Comment by gdpelican** [comment]
Hm, it's a good question... the original intent for this poll was to have _only_ a yes response (like 'I did it'), but we got plenty of feedback that people wanted to be able to respond in the negative ('sorry, but I can't make it')

My gut says that we want "<number of participants> out of <number of poll members>", to match the percentage below, and leave the chart visual to convey how many yes / no responses there are (so, 16 / 28 in the example above)

**Comment by BenDawes** [comment]
So suppose there are 30 members in my group, 5 respond Yes, 10 respond No, and 15 haven't responded yet. What should it display?

1) 5 out of 30 (50% of members have stated their position, 15/30). 
2) 15 out of 30 (50% of members have stated their position, 15/30). 
3) 5 out of 15 (50% of members have stated their position, 15/30).

and should the background of the results (the progress bar) be:

a) 1/6 complete ('Yes'-votes over total members asked)
b) 1/3 complete ('Yes'-votes over total responses received)
c) 1/2 complete (Responses received over members asked)

?

**Comment by gdpelican** [comment]
In that example, I'd say #2. The background should already be set up to have 3 'bars' in it, one for 'yes', one for 'no', and one for 'undecided' (although at present 'no' and 'undecided' are fairly similar shades of grey)

**Comment by BenDawes** [comment]
Okay, cool, forgot about the 3 bars.

Do we ever see users wanting to know exact counts of Yes/No/Undecided? If we go with (2) there'll be no way for users to easily surface exactly how many people chose Yes and how many No - and it'll be especially hard to judge when there are large membership counts.

**Comment by gdpelican** [comment]
We likely will at a point, (we don't so much right now...) but it's a design question for another day I reckon.

The easiest-to-make answer I can think of right now is to put an `md-tooltip` on the chart which appears after a second of hover (or a click on mobile), which has a small breakdown like

```
5 said 'yes'
10 said 'no'
15 undecided
```

I'd be happy for that to exist, but I'd merge something which just fixed the thing as it is now :)

**Comment by BenDawes** [comment]
https://github.com/loomio/loomio/pull/4488
