### ISSUE TITLE
Closing a discussion generates activity in Missed Yesterday

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#4546]
Either we should create an item in the email which says 'X marked this discussion as closed', or have it not appear in the email (since nothing that people really need to know about has happened)

**Comment by robguthrie** [comment]
Are you saying that closed discussions where someone comments should not be included in missed yesterday?

I think closed is just an indication to people that they should not add to the discussion from this point, and otherwise it's behaviour is the same as an open discussion. 

Locked discussions (on the map) wouldn't allow a comment at all, and thus not need to be filtered from email stuff anyway.

Or am I misunderstanding what you're saying?

**Comment by gdpelican** [comment]
Reported here: https://www.loomio.org/d/Gu3odjpT/new-feature-closed-threads/1

**Comment by gdpelican** [comment]
#4581
