### ISSUE TITLE
Send Missed Yesterday e-mails to invited email addresses to allow them to follow the group and nudge them into Loomio

### ISSUE THREAD

**Issue by juliencarnot** [loomio/loomio#4549]
In existing physical groups, even after talking about adopting Loomio together, I find that a sizeable minority will take weeks or even months to accept the invitation, and often need a coordinator to resend the link...

In the meantime, they miss the exchanges from the group and even physical meetings dates if the coordinator does not send the invites via another channel, and the group feels stuck on Loomio with new tools to use but no legitimity because not all the members can participate in decisions.

I think it would be easier for all if invited e-mail addresses were sent the content of Missed yesterday e-mails, with a custom footer, containing:
* a reminder of why they get this message ("coordinator @aaaaaa invited you to join on $date, but you haven't joined the group yet"), and maybe a way to signal abuse to admin in case this is a spammer using the Loomio platform.
* the invitation link ("Join the group to participate in discussions and decisions and adjust your level of email notifications").
* a decline invitation link ("Decline invitation if you do not want to join and do not want to receive these messages")

I think this would facilitate adoption and engagement in the first weeks, without exposing Loomio as a spam provider. It might still take time for some invited people to join, but at least they get more opportunities to get in, they're not cut from the group exchanges and the coordinators do not have to keep them updated by other means.

**Comment by robguthrie** [comment]
nice idea. It's not a super easy thing to do, but is arguably worth it, and not super hard either. Thanks for suggesting, let's think about it out loud.

**Comment by robguthrie** [comment]
This is technically much easier now that invitations are just group memberships. In fact we've had to write code to filter out unaccepted memberships from experiencing this behaviour.

Legally, I'm uncertain about what we can do, and I'd love some help navigating the legal stuff. The law in NZ says that you cannot subscribe people to mailing lists unless they confirm they wish to receive it. "double opt-in" it's called. It's to prevent people entering someone else's email address into a form and signing them up for stuff they don't want.

We do have the facility to "remind" an undecided, pending group member (ie: unaccepted invitation) of a proposal or poll. I think at some stage we had talked about including unaccepted members in the 'audience' of a group when you announce a thread or poll, but decided against it.

Perhaps a solution might be another audience button on the announcement form - "Members who have not accepted their invitations", so you can specifically bring them into the list to send them a thread or proposal. At least then it's user initiated every time, rather than an automated email, and the facilitator is aware of who they're bothering.

![image](https://user-images.githubusercontent.com/486367/40049264-7061dd82-585e-11e8-9304-bb92258e8ba5.png)

But I'm still not certain about this. Maybe your idea is the best. Rather than a "Reminder - Julien is still waiting for you to join Loomio" email, we send them a missed yesterday email, just once, a week or so afterwards, which details everything they've missed and explains at the top that they need to accept the invitation now or they'll continue to miss out.

**Comment by juliencarnot** [comment]
Thanks for your insight! I agree sending e-mails automatically with only an opt-out option is debatable and I really like your idea of letting the poster decide if she wants to notify invited but unconfirmed members too. In this case, the user is in charge and can take the blame for spammy behaviour rather than the platform, which is important.

In this case, could there be an additionnal paragraph in the message for these "invited but unconfirmed members" explaining why they receive this/who sent this, and a link allowing them to decline invitation to avoid further messages?

**Comment by juliencarnot** [comment]
In our 94 members coop, half of the invited people never accepted the invitation, no matter how hard we push for this (reminders, resending, IRL demos and help offered to get them started). So we've got half of the group not having a clue of what's happening online, missing info if we don't cross post it in a newsletter, and the other half that would be happy to participate, but we can't use polls or decisions without leaving an opportunity to participate to every member.

Some are already calling for other solutions, I hope that we'll be able to use all the loomio goodness, but for now any other new feature or improvements are becoming irrelevant in our context... Please let me know if we can help overcoming this issue!

**Comment by robguthrie** [comment]
How frustrating! I'm sorry but I can't help with a software solution. What are the other solutions people are calling for? Would they bother to use another platform but refuse to use Loomio? If so, why would they refuse Loomio?

I would suggest that you use the in person meetings to agree that Loomio is a place for some kinds of decisions, and if people don't participate, that's ok. Otherwise maybe pair up 1 user with 1 non user and have them all sign up 1 person each?

If people refuse to use Loomio I don't see how I can help.

Can you put group invitation links into the newsletter so anyone reading can participate if they wish? 

I'm sorry but we cannot break spam laws and make loomio a tool for sending emails without permission, that's a way bigger problem for us than this.

**Comment by juliencarnot** [comment]
Our demographic is probably 80% basic email users, 15% capable of signin in a platform and finding their way around, 5% power users. The calls for another solution are mainly "send us emails", nobody is suggesting another service but a lot are frustrated with the current solution.

I tried adding the invitation links in the newsletter, along with a paragraph describing why it is important to sign in: no significant gain in membership.

European mailing providers such as sendinblue.com provide options to admins to import e-mails into lists, by asking the admin to certify that she has obtained consent for this subscription. Every email have unsubscribe links and people can tell if they felt this was spam, which allows the platform to detect abuse and block abusing senders. This might be a bit borderline, but I think Loomio could help onboarding users by following a similar pattern, with very strict rules (say 2 invitees unsubscribe and indicate they have been subscribed against their will, the inviter gets blacklisted and can't send notifications for 2 weeks, and if 1 more unsubscribe and notify abuse, notifications are turned off for the group for 6 months).

I know Loomio can't do much to educate a reluctant user and that a lot of the non-confirmed invitees probably won't contribute to discussions soon, but I really think it is crucial that members of a physical group get information on what happens online and can decide if they want to participate in: the discussed subjects will eventually draw them in the discussion solution, not the contrary...

**Comment by robguthrie** [comment]
The problem I have is that this isn't something we're hearing from other users AND we have a recurring problem with people abusing our system by sending unsolicited emails.

I totally understand your proposed solution, but I don't think we can justify working on it right now.

One way of going about this would be setting up your own instance then manually accepting the invitations you've sent out on behalf of others. I'm happy to support you in doing this.

**Comment by robguthrie** [comment]
cleaning up old issues. I think we'll close this.
