### ISSUE TITLE
[UI] history cursor to ease down scrolling

### ISSUE THREAD

**Issue by jibe-b** [loomio/loomio#4558]
Long threads are hard to scroll down.

How about adding a [Discourse](https://github.com/discourse/discourse)-like history cursor on the UI?

![image](https://user-images.githubusercontent.com/6146483/36725780-b7dcff9a-1bb7-11e8-94ba-162d74a8e6db.png)

**Comment by gdpelican** [comment]
It's a good call. We've had a 'lintel' progress bar in the past, which has gone away since we moved to a nested / tree-like comment structure (which is a lot more difficult to represent in a simple view)

This is definitely on our list of things to improve though, and I agree it'll make the reading experience much better.

**Comment by robguthrie** [comment]
It's worth noting that we do have a "Jump to' dropdown.. A lot of people miss it, and we need to make it more obvious.

**Comment by jibe-b** [comment]
@robguthrie I couldn't find the "Jump to" dropdown, neither visually nor by searching for this string

![image](https://user-images.githubusercontent.com/6146483/36939752-fda9a294-1f36-11e8-8c4c-3043790c09ea.png)

May I ask you where to find it?

**Comment by robguthrie** [comment]
![image](https://user-images.githubusercontent.com/486367/36951732-a927dd9a-206b-11e8-8d52-ad5d5c9b1c53.png)

Whatever we do, it clearly needs to be at the bottom of the thread rather than the middle... and autoloading next page by default breaks that because the bottom is always slipping down the page.

So maybe we need to ask the user if they want to Load more, or jump to beginning or end. before we start the infinite scroll.

**Comment by robguthrie** [comment]
we did it!
