### ISSUE TITLE
Portuguese isn't appearing in app even when language is selected

### ISSUE THREAD

**Issue by gdpelican** [loomio/loomio#4569]
Can confirm by setting locale to `pt_BR`; the app is 60% translated, but all of the strings remain in English. I can conform that they appear to come over the wire from `/api/v1/translations?lang=pt_BR` correctly.

I believe it's a broken translation from a recent locale update, or _perhaps_ we're handling the slightly-odd locale string (pt_BR) incorrectly when parsing the results from the server.

**Comment by juliencarnot** [comment]
Reproducing this for all locales with dialects:
-   zh: zh_TW
-   nl: nl_NL
-   pt: pt_BR

The locales are displayed for visitors having these dialects as their preference, but once a user is logged in, English is displayed, even if this locale is set as their language on the profile page.

Only the client is affected, emails sent have set the locales_dialects strings.

Looking at the loaded resources, the good locale is loaded by the app:
https://www.loomio.org/api/v1/translations?lang=pt_BR
But a few milliseconds after, this one is loaded and since the file does not exist its content default to the en locale, I guess:
https://www.loomio.org/api/v1/translations?lang=pt-br

[/app/helpers/locales_helper.rb:44](https://github.com/loomio/loomio/blob/af0c89942e49cabcbfe0ce915923aac5e63cb9fd/app/helpers/locales_helper.rb) seems to normalize and replace the _ by an - for a logged-in user, which would explain this pt-br unnecessary loading, but I'm not sure how to fix this. @robguthrie

**Comment by juliencarnot** [comment]
It's a shame zh_TW has 100% coverage and nl_NL has 75% coverage but that users selecting these locales can't use their language due to this bug...

**Comment by robguthrie** [comment]
Thanks for the reminder!
