### ISSUE TITLE
Add a thumbsup reaction emoji option

### ISSUE THREAD

**Issue by patcon** [loomio/loomio#4590]
Hi there, Team Loomio!

In some other organizations I'm a part of, we have experimented with an online form of the "focussed conversation" facilitation method (a.k.a. ORID).

https://civictechto.gitbooks.io/working-open-a-pattern-library/decision-making-focussed-conversation-method.html

We are experimenting with using it as loose process within Loomio:
https://www.loomio.org/d/wcD7ePVn/how-should-we-carry-our-gear-around-

Currently, there is no "like" emoji except :heart:, which confuses how we use `:heart:` elsewhere in the format -- for marking "feeling" statements.

It feels like a missing tool to not be able to :+1: a comment. Is there an intentional reason it was omitted as an option? Might there be willingness to adding it, knowing that it can be helpful for meta-processes like this, and presumably other emergent uses of Loomio?

Thanks so much for everything!

PS - For now, we are using :raised_hands:, but that seems to overload how we use that emoji elsewhere in the community -- as a symbol of gratitude. Forcing us to overuse it here would seem to me to distort where we use it elsewhere :)

**Comment by gdpelican** [comment]
The reasoning is that it may clash with the 'thumbs up' from a proposal, but we've had enough feedback at this point that people are expecting a thumbs up reaction that I'm ready to put it in. @robguthrie?

**Comment by robguthrie** [comment]
I'd love to just say yes, but I'd want to be sure it does not confuse less advanced users. 

Scattering lots of thumbs up all over the screen (from both liked things, and the like button everywhere), when your task is to click the thumb up on the proposal, seems like a risky decision to me, and my concern is that we need to ensure that the voting buttons are not hard to find, even by people with low vision or cognition.. which is sometimes easy to forget about. 

I can imagine someone going into the page, clicking like, thinking they had agreed on a proposal and their vote not counting.

One thing (i notice) most open source projects have is lots of choice and not much strong design direction, and I'd like to be sure that we don't just offer more choice because we can, when it makes our signature action less unique and distinguishable.

Having said that I agree that the emergent use of thumbs up and down on comments sounds great and healthy.

We're trained by facebook that thumbs up is like, I wonder if we can find anything else that offers similar feelings/utility. 

I personally thought that smile face was a good alternative for like, and frown for dislike. Have you tried them, whats the feedback on those, @patcon?

**Comment by patcon** [comment]
I really feel for the "not confuse people" line of thinking. I really value the simplicity of Loomio.

Rebounding from that before your finer points @robguthrie: I wonder if another approach might be a deeper setting to "take the guardrails off" loomio. Like it could open up a set list of other options in one go. For example, things like [here](https://www.loomio.org/d/4cTRCoKe/loomio-and-the-advice-process). This "remove guardrails" might allow people to stay and learn on the main platform for a bit longer before taking the plunge into self-hosting. And keeping them on-platform helps Team Loomio learn more too, maybe? :)

So not a bunch of individual settings, but one toggle for all. And then, people working the support angle (official or community) could be like "hey first question: are you in advanced mode?" And know that in that edge-case, more attention is needed to certain parts of working together.

----

As for your "smile"/"frown" suggestion, that's a great idea, and worth experimenting with. There's something about them that feels more... "emotional"... like about a feeling someone is having about the fact/feeling/idea statement, rather than an agree/disagree expression. That might mislead people. Like if someone agrees/disagrees with a factual statement in our meta-system, a smile/frown seems an odd way to express that.

 But I think it's a great suggestion in the meantime, so thanks!

re: +1/-1 reactions via thumbs emoji. In terms of design, perhaps the reaction emoji could be the standard "yellow hand", and then the docs could always say "green thumbs up", "red thumbs down", and that would subtly distinguish it. Though yes, there is still the added burden that I empathize with.

**Comment by robguthrie** [comment]
Thanks.

Minor reply point. Colour is also something not all users can perceive, so distinguishing based on that is fragile.

We have a strong commitment to accessibility - it's a core value that takes work but actually makes the app better for everyone. It also has a nice side effect of being good for business. 

Keeping Loomio simple takes work, and also requires more consensus among the team, but if we're going to become a really simple and impressive app, we've got to work towards it.

**Comment by gdpelican** [comment]
Hm, I don't quite think it's fair to frame this as 'we require more consensus among the team to keep Loomio simple'; I don't really think that's the conversation that's happening here. This just reminds me so much of reacting to user feedback during the earlier days of Loomio (editing comments, multiple proposals at the same time, truncating comments), where a team member has a strongly held belief that they're not willing to test in the app, and so when users ask us about it (and they do, somewhat frequently), instead of just giving the users what they ask for we have several paragraphs explaining our strongly held belief, which is never tested or confirmed.

In all of the cases before, we built and deployed those things eventually, and never heard about them again. So, I'd gently encourage you to consider putting in this oft-requested feature, with the knowledge that it's really easy to revert if there's reports of confusion around it, in which case we'll have a lot more information about why it's confusing and what we can do to ensure it's not (and, to consider that it's possible that we're causing more confusion by making people wonder where the thumbs up they're expecting is each time they go to react to something, than we're preventing by having someone think they voted when they haven't)

Would you be up for putting a 👍 in for reacting to models that aren't decisions?

**Comment by robguthrie** [comment]
Yea, I would be ok with (even excited about) using it for models that are not decisions.

Generally I do think that it takes work to get consensus on what features might detract from the simplicity of the user experience, and how it takes discussion to find a good approach. This thread is an example of that.

Sorry if I reminded you of a stubborn team member. I'm finding that comment challenging, and feel it was unfair.

**Comment by robguthrie** [comment]
Anyone following along. James and I have had a good in person chat this morning.

I've given some time to reconsider here..

In user testing we've had plenty of feedback that the reaction button looks currently like an invite people button. so I don't really have a good track record of avoiding confusion about this particular icon.

![image](https://user-images.githubusercontent.com/486367/37577803-3beb57b4-2b99-11e8-8d5e-d195d1dd839d.png)

Thinking about adding the thumbs up/down reactions, and confusing them with voting - we avoid potential confusion if we just ensure that thumbs_up is not the emoji menu button just a secondary option. (which I realise now was never the intention, but for some reason I imagined it was). The only thumbs up _button_ someone looking at the screen would see would still be a "vote agree" button, and it would be much bigger.

The value we keep hearing users ask for seems pretty real, the potential for confusion about what action to take seems pretty low when I rethink it.

So, rethinking it, I don't have an objection to adding them - and I wonder what people think we should change the reaction button to be?
