### ISSUE TITLE
Translate context broken

### ISSUE THREAD

**Issue by mhjb** [loomio/loomio#4600]
Visit thread https://www.loomio.org/d/UDjrcstN/probl-me-sur-une-discussion
![image](https://user-images.githubusercontent.com/1380991/37735626-8200e36a-2db3-11e8-8cf7-31ba449cbb92.png)

Click translate icon…
![image](https://user-images.githubusercontent.com/1380991/37735618-782477c6-2db3-11e8-8352-c8694544c533.png)

**Comment by juliencarnot** [comment]
Confirmed, but I'd argue against fixing this and for removing this button and automatic translation feature (that only appears when you set your language to English). I don't see real-world groups using loomio in several languages and relying on automatic translations to make decisions together online, and if needed, I'd let the user choose their translation service and copy-paste text, so that they're fully aware they are relying on a machine to understand what others say... As a bonus for group privacy, the translation service won't know the URL of the discussion and the origin of the text.

**Comment by gdpelican** [comment]
Alright, this is now fixed.

Inline translation's a relatively common forum-style feature (Discourse has an [official plugin](https://meta.discourse.org/t/discourse-translator/32630) for it, for instance)

Bing doesn't receive anything other than our host (loomio.org) and the text to translate (no discussion URL or personally identifiable information), although reading their privacy policy is making me a bit uneasy about whether they store translated text or not, and whether they can share that information or not. I'd be really open to a group setting which disallows people to translate text within that group.
