### ISSUE TITLE
Bug: Screen jumps up/down erratically while typing on Android app

### ISSUE THREAD

**Issue by lukeflegg** [loomio/loomio#4729]
https://youtu.be/3v836Kb2Sa0

**Comment by robguthrie** [comment]
This is related to the autogrow feature on the md-textarea. It's such a terrible bug, it happens on desktop platforms too but it's less annoying because there isn't an onscreen keyboard.

I think we need to treat this as critical. Maybe disable autogrow and use fixed size input with user adjustable resize (like here on github)

**Comment by robguthrie** [comment]
tracking this via #4743
