### ISSUE TITLE
SEO room for improvement

### ISSUE THREAD

**Issue by rdbartlett** [loomio/loomio#4967]
I googled "Loomio UNCTAD" and got these unexciting results:

![image](https://user-images.githubusercontent.com/970124/47870758-3a0c8500-de02-11e8-886d-35ac0aaec067.png)

**Comment by robguthrie** [comment]
oh you're talking about the "loomio requires javascript to work" line? yea good call. Thanks

**Comment by gregorykan** [comment]
https://northcutt.com/seo/how-the-noscript-tag-impacts-seo-hint-be-very-careful/

**Comment by gregorykan** [comment]
TLDR; the contents of noscript tags will always be read by search engines. there are workarounds such as using an image instead of text inside the noscript, but this can be considered as 'cloaking' behaviour by google.

consensus seems to be that in this day and age, where javascript is increasingly ubiquitous, you simply don't use noscript tags.

**Comment by robguthrie** [comment]
Actually we have meta tags for google to display, it looks like it wants them written slightly differently.

We've deployed a fix now. Thanks for the heads up!
