### ISSUE TITLE
Material buttons do not work on Firefox and GMail for Android

### ISSUE THREAD

**Issue by brylie** [loomio/loomio#5014]
Please test the sign-in flow, and all other features on Firefox for Android and the Android GMail app. In both cases, none of the sign in buttons work on the Loomio site (not the email link). Similarly any material button, such as "save new password", "contact Loomio", "edit profile", etc. "fails to have any effect other than the material design animation.

**Comment by robguthrie** [comment]
Hi @brylie I've just gone and done some testing but cannot replicate the issues you're having. Can you please tell me the specific browser and android versions you're using?

Thank you!

**Comment by robguthrie** [comment]
Hi @brylie Sorry you've had such basic problems.

I'm having trouble replicating this, I've tested on Firefox 63 on ios and Android, it's not perfect, the keyboard does not show when you click the input field, because it's already focused... but it's not broken and the buttons all work. Are you still having problems, is there any more info you can tell me about this?

**Comment by brylie** [comment]
Well, I logged in on Chromium for Firefox. I will re-open the issue, if it happens again.
