### ISSUE TITLE
Ranked choice numbers display is off

### ISSUE THREAD

**Issue by lorelei1** [loomio/loomio#5139]
First of all, the "1st, 2nd, Total" column names are overlapping "Load more" so it's really hard to see them. 
<img width="829" alt="screen shot 2019-01-11 at 12 35 23 am" src="https://user-images.githubusercontent.com/38163206/50986620-e58c3100-1539-11e9-8fa4-915523d5d002.png">

Then also, I know that option 3 has a couple votes, you can see this by the color bar and also responses below... but the numbers display zero.

**Comment by robguthrie** [comment]
Hi, thanks for getting in touch.

Option names don't work well with long text. I would recommend you change your option names to be very short, ie:
- Growing the network
- Engaging blockchain
- Culture differences
- Open source funding models

I think this affects everything else in the bug report. It looks like the totals rows are misaligned with the graph rows. 

I think I'll add a restriction to the number of chars on a poll option, because that would have prevented this problem in the first place.

How does that sound?

**Comment by robguthrie** [comment]
closing as very old
