### ISSUE TITLE
Corrupted Group data import 

### ISSUE THREAD

**Issue by syamgk** [loomio/loomio#5280]
By following the steps mentioned in the documentation here 
https://help.loomio.org/en/user_manual/groups/data_export/
we exported the data in JSON format and imported it on our own hosted instance of loomio(https://codema.fsci.org.in) after migration thread list is coming properly but discussions(some of them gets open and loads description successfully) and comments are not.
Could you please suggest us the optimum way to fix the same?

logs on our instance 
```
GroupExportService.import('/import/fsci.json')
=> ["groups", "users", "events", "notifications", "documents", "reactions", "memberships", "membership_requests", "discussions", "polls", "poll_options", "poll_did_not_votes", "poll_unsubscriptions", "outcomes", "
stances", "stance_choices", "discussion_readers", "comments"]
```

Thanks for supporting the export feature, it's brilliant
Keep up the good work!

**Comment by robguthrie** [comment]
Hi, I'm not able to see enough information to help.
The output you've pasted is correct.

Was your instance empty before the import?

**Comment by robguthrie** [comment]
Sorry for the inital delay in reply. I'll try to be more responsive now.

**Comment by syamgk** [comment]
> Hi, I'm not able to see enough information to help.
> The output you've pasted is correct.
> 
> Was your instance empty before the import?
no, the instance had other groups which are listed here: https://codema.fsci.org.in/explore 
and this https://codema.fsci.org.in/g/esPoQ4S0/free-software-community-of-india-fsci- is the group I exported from loomio.org and imported to this instance

**Comment by robguthrie** [comment]
Hrrmm. I'm not sure what the problem might be. 

Are you running the docker container, or your own server?

So, to clarify, you're seeing users, memberships and discussions, but not comments?

Can you login to the server (see `rails c` instructions on the loomio-deploy readme) and run
 
```
Comment.count
```

Maybe try something like 

```
Discussion.last.comments.count
```

Also can you open the inspect tool in your webbrowser and check if there are any console errors happening when you try to load the pages?

**Comment by robguthrie** [comment]
Any more info on this? I'd love to help but I don't know where to begin without knowing what data is missing.

**Comment by necessary129** [comment]
Hello.

This is filling up the `docker-compose logs`:

```
loomio-db      | STATEMENT:  INSERT INTO "discussion_readers" ("user_id", "created_at", "updated_at", "discussion_id") VALUES ($1, $2, $3, $4) RETURNING "id"
loomio-db      | ERROR:  duplicate key value violates unique constraint "index_discussion_readers_on_user_id_and_discussion_id"

```

And the JS console has:
```
TypeError: "this.author(...) is undefined"
```
filling it up

**Comment by robguthrie** [comment]
What group (url please) are you trying to export? I'll have an attempt myself if you give me permission.

**Comment by robguthrie** [comment]
I've just manually tested a group import and it works well for me.

When you give me your group ID, I'll test that out too.

For reference.. I did this:
dropdb loomio_development  
createdb loomio_development 
rake db:setup  
rails c
GroupExporer.import('myfilename.json')

**Comment by kannanvm** [comment]
sorry for the late feedback.
https://www.loomio.org/g/esPoQ4S0/free-software-community-of-india-fsci- is our group id.
We are actually importing into a currently existing db which has users and logins, so `dropdb` is not feasible for us.

**Comment by robguthrie** [comment]
I think the discussion_reader problem can be ignored. It's not important, but the `author is not defined` is a big problem and that's why discussions and comments are not showing up.

The problem is likely to be that users are already registered in your system, with the same email address but a different user_id than what is in the in exported data. 

If a record cannot be inserted during import (due to email address already taken), then it is ignored, so there are discussion and comment records that are being imported and pointing to a user_id that has not been imported, because the user record clashed with an existing one with the same email address.

How many user records are you trying to import? I would suggest that you open the json file, and find each line beginning with 

```
{"table":"users","record":{"id":151,"email":"someone@address.com" .....
```

And change the email address to something like `someone@address.com1`, so then all the users get imported and the discussions and comment authors are present.

Then you can merge the imported user accounts into the existing user accounts.. we have a function for that in the /admin panel for each user. So you could go through your users list and merge each imported user into the existing user.

![image](https://user-images.githubusercontent.com/486367/56935545-c09de700-6b45-11e9-8bc9-b214f7df24cb.png)

That should fix it.
