### ISSUE TITLE
Sub-groups are not clearly visible

### ISSUE THREAD

**Issue by tcharlss** [loomio/loomio#5282]
Hi,

We are testing Loomio in our community (an open-source CMS).
The main group represents the CMS and all its community, and there are sub-groups dedicated to each new project, with a limited number of active members.

Unfortunately, a lot of newcomers struggle to notice these sub-groups, when they land on the main group page.
Indeed, they are presented a bit like a "secondary" bit of information, located on the side.

In my view, they are a very important information, representing the structure of the group.
As such, I think they sould be displayed in the main section of the page, at the center, and before the active discussions.

**Comment by robguthrie** [comment]
If you ensure that the subgroups are closed (rather than secret) and tick "Members of (parent group name) can see private threads" then the threads of your subgroups should appear in the main column of the main group. You could even choose to pin some of the threads to keep them on top.

Does that help with your engagement problem?
