### ISSUE TITLE
Invited users' email addresses are exposed to other group members

### ISSUE THREAD

**Issue by sky-xo** [loomio/loomio#593]
Given a public group exists
And all members can invite other users to the group
Then all group members can see the invited users' email addresses

This is okay for medium-sized groups, but will become a privacy issue when we scale. We'll need to think of an alternative here. Perhaps completely hiding the invited users list from everyone except admins? It's quite an easy solution that might just do the trick.

**Comment by juliencarnot** [comment]
@robguthrie just noticed this and find it quite problematic for privacy, and confusing because when the invited people accept the invitation, the e-mail address can no longer be seen (except in a gold group). I'd rather restrict the invited emails list to coordinators only. Should we reopen this issue?
