### ISSUE TITLE
Any discussion on plugins for Vue / loomio 2.0?

### ISSUE THREAD

**Issue by chmac** [loomio/loomio#6175]
I [read](https://help.loomio.org/en/dev_manual/plugins/) that " it’s unclear how we’ll support plugins for the client right now" under the new Vue frontend.

Is there any discussion on approaches to this?

Is there a place where discussions of this nature take place? As a developer I'm struggling to see where the technical decision making takes place, what the thinking that goes into it is, and so on. Perhaps that's deliberate, and loomio is built by a specific organisation and doesn't seek external contributors, not sure.

**Comment by robguthrie** [comment]
Hi @chmac, thanks for getting in touch.

We had a plugin system in the angular client - nobody external to Loomio used it (that I know of) and it made development harder, not easier, particularly because it meant managing multiple git repositories and testing became unreliable.

Also a plugin system means we need to make guarantees to plugin authors about the application, the design of the UI in particular, which I'm not really prepared to make at this stage.

We're a very small team, so we focus on developing an end user experience, not a 3rd party developer experience. That said, I'm happy to support someone to work on Loomio, but I need to know what they want to achieve before a create a development framework for them.

So if you have a plan, please let me know what you want to do, and we can discuss how to do it in a constructive way, which may eventually turn into the next plugin system.

**Comment by chmac** [comment]
@robguthrie Understood, thanks for the update.

I was mostly looking into how folks have implemented frontend plugin frameworks. We're working a [dreams update](https://github.com/Edgeryders-Participio/multi-dreams) and looking for inspiration of how other folks have solved this problem. Most of the projects using dreams are also using loomio, so I figured this would be a good place to start. I'm sure there will be loomio plugins in the future, but I'm not sure what they would actually do as of now...

**Comment by robguthrie** [comment]
Cool. Happy to discuss ideas when you get to the use-case stage.
