### ISSUE TITLE
Notification settings are always disabled for users

### ISSUE THREAD

**Issue by farx** [loomio/loomio#6216]
Heyhey!

Since the 2nd of December our Loomio instance at talk.theborderland.se no longer sends out notifications to any users. For all users it is disabled in settings and cannot be re-enabled. Any attempts to re-enable it just wont be persisted.

Steps to reproduce: 
1. Log into talk.theborderland.se
2. Go to Notification Settings in the main menu
[See that all radio buttons for "Notification preferences for all groups" are unchecked]
3. Set notification radio button in group "Notification preferences for all groups"
4. Press update
5. Refresh the page
[See that all radio buttons for "Notification preferences for all groups" are unchecked again]

**Comment by robguthrie** [comment]
Oh no!

The "notification preferences for all groups" will always start without a value (it's just so people can reset all groups at once). So that's not the right place to start.

I think we need to look at your docker logs. What do you see when someone fires an email?

One thing to note is that the background job system has been changed from DelayedJob to SideKiq.. (I'm not sure if you're using an image with this change or not) I would compare the docker-compose.yml you're using with the one in loomio-deploy and see if there is anything that needs updating.

If you like we can pair on this, I hate the idea that people are not getting notifications when you need them, so I'm keen to help. email me rob@loomio.org we can make a time to look at this  (something between 1pm and 11pm NZ time tomorrow?).

**Comment by farx** [comment]
Thanks for the leads Rob. The system can send emails out. Its just the notification-emails that is bork. 

I'll have a look at the logs and the docker-compose and try to figure it out today. If I can't fix it I'll drop you a line @ your email.

**Comment by aerugo** [comment]
Can confirm @farx, and clarify that when we looked at it, sending emails to other users through the contact form works fine. I guess that is consistent with it being a problem with the background job system.

**Comment by farx** [comment]
This issue was resolved by adding a link to the redis service in the app service defined in the deployer docker-compose.yml

Thanks for the help finding the root cause!
