### ISSUE TITLE
Performance: Current thread rendering architecture is not capable for 100+ members / 20 polls in thread

### ISSUE THREAD

**Issue by gramotei** [loomio/loomio#6236]
1) it is hard to navigate because each polls add 100+ entries to the thread per poll
2) For each of that 100+x20 entries it sends mark_as_read request that returns tons of data with current state (more than 100KB json (after decompression)) that add works to Angular processing
3) Also that results to DoS attack on backend. For example loomio.org server was returning 503/520 errors when we was trying to vote yesterday

**Comment by robguthrie** [comment]
Thanks for getting in touch, @gramotei . I've been paying attention and looking at what I can do.

I've fixed the server so it does not return 500 errors. Here are the results:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/486367/72878320-99381b80-3d5f-11ea-8ae7-189729e45584.png">

I'm updating so mark_as_read does not return data, as it's not required. This will be deployed in a few hours.

The interface is needing an update so that we don't display more than 20 (or so) nested items (ie: only the last 20 votes per poll) unless requested by the user, I'll be working on this shortly.

I'm keen to hear how else you think I can improve things quickly. Thanks for using the system and giving feedback.

**Comment by gramotei** [comment]
I've checked the source code before creating this issue but can't see what can be easily done. at the moment we're sending newsletter to our community members with a 'hack' from our clever guy. The hack is to run this in the browser console:

```document.querySelectorAll('.event-children').forEach(e => e.style.display = 'none');```

After running that I was able to vote late night yesterday

**Comment by robguthrie** [comment]
Nice work. I'm so sorry it's not working well for you. I'll implement something to limit replies/votes when things are this long, as soon as I can. Hopefully will have something by the end of the week, but I can't rush it any more than that.

**Comment by robguthrie** [comment]
@gramotei what about if you try changing the thread to Flat list mode? (click the "x responses, oldest first" text)
<img width="619" alt="image" src="https://user-images.githubusercontent.com/486367/72904366-a7079400-3d93-11ea-8590-936d17edc363.png">

**Comment by robguthrie** [comment]
Update, I'm still working on this, it's been a busy week!

**Comment by robguthrie** [comment]
We've sorted these perf issues out now. More to come but I want to close this thread.
