### ISSUE TITLE
Deleted comments cannot be undeleted, nor history viewed

### ISSUE THREAD

**Issue by madduck** [loomio/loomio#6639]
When a comment is deleted, it seems to become inaccessible forever. This means it cannot be undeleted, nor is the history still accessible (nor can pins be removed: #6638). I don't think that's right, and a deleted comment should not only still expose the edit history prior to deletion, but should also be undeletable.

**Comment by robguthrie** [comment]
Hi @madduck, 

Until recently, when comments were deleted, they actually were deleted from the database for completely. All reference to them was removed from the thread too. This is because it's a legal or ethical requirement to properly delete stuff some times.

However many people got confused and did not know why comments went missing, and more regularly the request is to provide a papertrail of the removal of a comment, rather than the complete erasure.

2 weeks ago we put in the server side work to instead, keep the comment and it's history and just put a placeholder in the thread to acknowledge it's removal. That's why you see "Item removed" now.

So the feature is WIP, but deployed (so that the papertrail is in place ASAP), I was waiting for more insight into when it's appropriate to make undelete and history functions available for a deleted comment. 

Specifically , to make progress on your request:

- Should everyone (who could see it before the delete) be able to see the history of a deleted comment or just admins or just the author? 

- Should admins be able to undelete a comment or just the author?

**Comment by madduck** [comment]
Yeah @robguthrie, this is fun stuff. I personally take a very simple stance in that I say that information can never be deleted, and giving users the impression of being able to delete comments (as happens frequently on Slack/Whatsapp/Twitter/etc.) bears the potential of conveying a wrong sense of reality. Some people will have already read the information. Maybe someone screenshotted it. Maybe I have a screen scraper that already archived it all…

I see the legal angle. And this makes me think that the best solution might be to differentiate between deletion (not to be confused with hiding as in #6631) and purging. The former leaves a papertrail, including the ability to view history, and undelete. Purging OTOH should be reserved to admins and would exhibit the behaviour currently in place ("the item has been irrevocably removed by …").

**Comment by madduck** [comment]
> Should everyone (who could see it before the delete) be able to see the history of a deleted comment or just admins or just the author?

I think everyone who previously would have seen the comment should be able to see the entire papertrail.

> Should admins be able to undelete a comment or just the author?

I think admins should be able to do anything really. If they can't be trusted to do this wisely, they ought not be admins.

**Comment by robguthrie** [comment]
Happening in #6640

**Comment by robguthrie** [comment]
You can now "unremove" comments
