### ISSUE TITLE
Thread starter shows a different author than the original

### ISSUE THREAD

**Issue by coopchange** [loomio/loomio#7077]
I think you edited my thread context and now it shows you as the author/holder of the thread:
https://www.loomio.org/d/8ADqtkMl/improving-office-bike-parking
<img width="1440" alt="Screen Shot 2020-11-09 at 6 01 51 PM" src="https://user-images.githubusercontent.com/18379380/98502089-051b4e80-22b6-11eb-806b-a3d2af915e5a.png">

**Comment by coopchange** [comment]
@robguthrie it'd be awesome to hear back about this one before our demo #reassurance (but i get if that is not possible; cheers)

**Comment by robguthrie** [comment]
Hi John,
Yes, I changed this, though it would be nice to see a change of face on some long running threads.. however I realise that was a bad idea.. we'll introduce a strip of user avatars to show participation later on.

The actor in the event of discussion edited (in the "edited" thread item and email notification) will be the person who edited it, but the author of the discussion will not change.

It's going to be reverted/fixed in 2.5.1
