### ISSUE TITLE
Cannot change vote reason in ranked choice

### ISSUE THREAD

**Issue by despens** [loomio/loomio#8043]
When changing my vote in a ranked choice, I am able to change the ranks around and save the changes, but any changes to my "reason" text do not seem to get saved. A PATCH request with the correct HTML is sent, but even reloading the page won't display the updated text.

Latest Loomio stable, 2.11.0

**Comment by robguthrie** [comment]
Yikes, ok I'll have a look.

**Comment by robguthrie** [comment]
I'm able to vote on ranked choice with a reason, and then update my vote with changes to rankings and reason multiple times and it works fine on 2.11.2.

I might have introduced a bug around 2.11.0 with this, because the text editor went through major changes. Could you please update to 2.11.2 and try again?

**Comment by robguthrie** [comment]
closing unless it is reported again
