### ISSUE TITLE
Ordering of pending polls in Dashboard

### ISSUE THREAD

**Issue by jmallach** [loomio/loomio#8244]
Currently, pending polls listed in your dashboard are ordered by creation date.

Please reorder them by closing time by default, as it probably makes more sense to see those that are closing imminently than those that might be older but have a closing date of months ahead.

**Comment by pabelenda** [comment]
I would say also that having the label filtering available could be very helpful

**Comment by robguthrie** [comment]
@jmallach will do

**Comment by robguthrie** [comment]
@jmallach just getting back up to speed now. Happy new year!

I'm a little confused about this issue because polls _are_ ordered by closing date. I think they've always been ordered this way on the dashboard.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/486367/150717013-31dbe956-a650-441e-95fe-e4b2b65e8386.png">

**Comment by robguthrie** [comment]
I think we're all good here.
