### ISSUE TITLE
Polls that passed their closing date are offering to "close early"

### ISSUE THREAD

**Issue by despens** [loomio/loomio#8365]
Polls with a closing date do not close by themselves, but keep displaying the "close early" button.

It is still possible to call the editing interface and to "change your vote," but none of these changes will be accepted by the backend.

This is happening with v2.11.12.

**Comment by robguthrie** [comment]
I would say that your cron job is not running.  It's main job is to close polls :)

https://github.com/loomio/loomio-deploy#install-crontab

Let me know if the line is in-place, after that I'll have a think about debugging it. Ideally we would come up with a docker-encapsulated way of running cronjobs so it's not a manual install step.

**Comment by despens** [comment]
Yikes, you are right! I now realized I was working on a system than came without cron pre-installed.

Thank you very much, and sorry for disturbing.

**Comment by robguthrie** [comment]
no problem! good luck!

**Comment by bobemoe** [comment]
I had this issue too, even though my cron job was configured correctly and had been working for a while after setup:

`0 * * * * /usr/bin/docker exec loomio-worker bundle exec rake loomio:hourly_tasks`

After some time, it stopped working intermittently. In the cron output I saw errors like:

`OCI runtime exec failed: open /run/user/0/runc-process2862258205: no such file or directory: unknown`

Weirdly, as soon as I logged in to diagnose the problem, it started working again. Turns out `/run/user/0/` only exists when the root user has an active session, and Docker's behaviour of allocating a pseudo-TTY when using docker exec depends on that directory being present.

Changing to docker compose run worked for me, make sure you specify the correct project directory containing your `docker-compose.yml` file:

`0 * * * * /usr/bin/docker compose --project-directory ~/dockerfiles/loomio-deploy run --rm worker bundle exec rake loomio:hourly_tasks`

After this change, the job ran reliably regardless of whether I was logged in.

**Comment by robguthrie** [comment]
@bobemoe bobemoe - does the OCI runtime exec mean you're not using docker?

**Comment by bobemoe** [comment]
@robguthrie I am still using Docker with the docker-compose provided by https://github.com/loomio/loomio-deploy

The error with `OCI runtime exec failed: open /run/user/0/...` is actually a result of how `docker exec` works under the hood.

When you use:

```
docker exec loomio-worker bundle exec rake loomio:hourly_tasks
```

…it tries to attach to an already-running container and allocate a pseudo-TTY (even if you don’t explicitly use `-t`). Under the hood, Docker uses a lower-level runtime called `runc`, which attempts to create temporary control files like:

```
/run/user/0/runc-processXYZ
```

The problem is that `/run/user/0` only exists when root has an active login session, and cron jobs often run in headless environments with no session. So the command fails because the required runtime directory doesn’t exist.

When I switched to:

```
docker compose run --project-directory ~/dockerfiles/loomio-deploy --rm worker bundle exec rake loomio:hourly_tasks
```

…it worked because this starts a fresh one-shot container rather than attaching to an existing one. It doesn’t rely on `/run/user/0` or any session-based environment. I did originally try `docker run ...`, but that didn’t work in my case because it didn’t load the right Docker environment or have access to the required network and volumes. `docker compose run --project-directory ~/dockerfiles/loomio-deploy ...` solved that by using the correct config from `docker-compose.yml`.

So the `OCI runtime` error is coming from Docker's internal runtime, and switching to `docker compose run` avoids the conditions that cause it.

I may be an edge case because I am on Devuan Linux without systemd which could affect cron and the /run/user interactions.
