### ISSUE TITLE
Display list of tags in alphabetical order in the threads view

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#8448]
When there are multiple tags for a group, finding a specific tag can be hard because they are not displayed in alphabetical order:

<img width="1273" alt="Screen Shot 2022-03-08 at 10 59 17" src="https://user-images.githubusercontent.com/333447/157252938-0214db81-9343-4d16-983a-e05192161e2b.png">

**Comment by robguthrie** [comment]
Hi @anarute. It turns out that you can change the order of tags via drag and drop. 

When you are adding or editing tags, there is a handle (8 dots) you can drag to reorder the tags. This order is used in the dropdown menu.

This might be unnecessary, but I thought I'd mention it before I change it to be alphabetical.

**Comment by anarute** [comment]
@robguthrie that solves for us then, thank you.

**Comment by anarute** [comment]
I'm experiencing this error when trying to reorder the tags:

![Screen Shot 2022-11-17 at 12 56 11](https://user-images.githubusercontent.com/333447/202440234-6bcb09f0-8c9c-40b9-b989-fa6867f17ed8.png)

Running locally with node v14.18.0 in Chrome
