### ISSUE TITLE
When a vote is changed in Loomio, the past vote keeps appearing

### ISSUE THREAD

**Issue by anarute** [loomio/loomio#9935]
I think this is a recent change: when someone votes in a poll and changes their vote after, both votes keep appearing in the list, they are not counted twice but the old comments (reason to vote) are still visible, causing confusion.

As a user I expect the old vote is not shown anymore, only the current vote of the person.

**Comment by robguthrie** [comment]
Hi @anarute this is because we've added reply (comment) to votes. We had many cases where someone would vote, then there would be replies, and then the person would change their vote.

If there isn't a new record when they change their vote, then the discussion on their original vote does not make sense.

**Comment by anarute** [comment]
But then doesn't make more sense to also hide related comments?

Because now what's happening is that people are getting confused between old and new votes and also who votes get's the bad sensation that anything they write is set in stone as there's no way of removing their past comment.

**Comment by robguthrie** [comment]
Oh... maybe I'm misunderstanding. Are you talking about poll page or thread page? Poll page should only show latest votes - I can fix that.

**Comment by anarute** [comment]
I'm talking about the thread page, for example: 

![Screenshot from 2023-10-16 10-08-51](https://github.com/loomio/loomio/assets/333447/50bc7af8-553e-4fbc-a92b-f705aec20e6c)

In the screenshot my current vote is the third one, but the others keep showing and I can't erase them

**Comment by robguthrie** [comment]
Ok thank you. Happy to work on ways to make this better.

Did you notice that when you reload the page, the old votes have "Superseded" next to them?

<img width="774" alt="image" src="https://github.com/loomio/loomio/assets/486367/95fdbadb-6449-4f3f-9b1f-8d717b1cc1cf">

The main constraint here is that if a vote has replies, or the vote has information that others have referenced, then removing it when the user changes their vote breaks the conversation.

For example - in your screenshot - if you explained why you changed your mind for each vote, it would make a lot of sense to see each vote.

So I want to think carefully about what the real issue is, and what steps to take. I personally think it's really important to see that someone changed their mind, and why.

If we allow you to delete your previous votes, what happens to any replies associated to them?
What about if I did a better job of highlighting that the vote was superseded/replaced?

**Comment by robguthrie** [comment]
One other thing to mention, is that we don't show an entry in the thread if there is no "reason" with the vote. So this is not a problem for votes without reasons, or for polls with "reason" disabled.

**Comment by anarute** [comment]
Hi Rob, sorry for the delay, I'm running the latest release 2.21.1 and I don't see the supersed label:

![image](https://github.com/loomio/loomio/assets/333447/b6282f16-65df-45a8-b8ee-863bb530ca97)

In any case, if you feel it's important to keep displaying the old votes, that's ok unless the person has the opportunity to delete them in case they really don't want to show their past vote.

I personally still find very confusing and many of our users were confused as well and some frustrated that they couldn't hide their past comment.

**Comment by robguthrie** [comment]
Thanks @anarute - as always, I really appreciate your feedback. I hope you know that I'm committed to making the best use of your input. I'm just trying to balance the constraints of having replies to votes (which are totally valuable)

I'll check why superseeded (can you think of a better word? outdated? replaced?) isn't showing for you.

And I'll introduce a discard/delete function. Some questions: If someone has replied to the vote then would you expect delete to be available. If it is available, would you expect it to delete the replies too?

**Comment by anarute** [comment]
> I'll check why superseeded (can you think of a better word? outdated? replaced?) isn't showing for you.

Good question, maybe "outdated"?

>  Some questions: If someone has replied to the vote then would you expect delete to be available. If it is available, would you expect it to delete the replies too?

Yes, I think it makes more sense to discard them too. Thank you!

**Comment by robguthrie** [comment]
Hi @anarute I think I've found a good solution here.

Firstly, I've changed "superseded" to "Outdated".
Next, Outdated will show up properly when you edit a vote.
Last, We only create a new entry in the thread if the stance had replies.

So If someone just changes their stance (vote) a few times, it won't make multiple entries in the thread, you'll just see the changes in the "edit history" window - but if their vote had replies then we make a new entry in the thread.

So I don't think we'll need to allow deleting/discarding stances after all.

Let me know if that's a good enough solution

**Comment by anarute** [comment]
Sounds great, thank you!

**Comment by anarute** [comment]
Hi Rob, we just updated our instance to the latest release and I don't see past votes with the "Outdated" label. When there is no reply the old vote is hidden, which is expected, but if it has comments it keeps showing with the current vote and it's hard to know that the person updated it.

[Screencast from 2023-12-01 17-25-14.webm](https://github.com/loomio/loomio/assets/333447/ade8214b-3f5e-4579-90f1-9af176bda03a)

**Comment by robguthrie** [comment]
Thanks for pointing this out, again :-)
